// Code generated by ent, DO NOT EDIT.

package syncevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// ModifiedAt applies equality check predicate on the "modified_at" field. It's identical to ModifiedAtEQ.
func ModifiedAt(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldModifiedAt, v))
}

// SourceSystemID applies equality check predicate on the "source_system_id" field. It's identical to SourceSystemIDEQ.
func SourceSystemID(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldSourceSystemID, v))
}

// ProcessorVersion applies equality check predicate on the "processor_version" field. It's identical to ProcessorVersionEQ.
func ProcessorVersion(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldProcessorVersion, v))
}

// ReprocessOf applies equality check predicate on the "reprocess_of" field. It's identical to ReprocessOfEQ.
func ReprocessOf(v uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldReprocessOf, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldEndedAt, v))
}

// RecordCount applies equality check predicate on the "record_count" field. It's identical to RecordCountEQ.
func RecordCount(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldRecordCount, v))
}

// HighWaterMark applies equality check predicate on the "high_water_mark" field. It's identical to HighWaterMarkEQ.
func HighWaterMark(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldHighWaterMark, v))
}

// ErrorSummary applies equality check predicate on the "error_summary" field. It's identical to ErrorSummaryEQ.
func ErrorSummary(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldErrorSummary, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// ModifiedAtEQ applies the EQ predicate on the "modified_at" field.
func ModifiedAtEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldModifiedAt, v))
}

// ModifiedAtNEQ applies the NEQ predicate on the "modified_at" field.
func ModifiedAtNEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldModifiedAt, v))
}

// ModifiedAtIn applies the In predicate on the "modified_at" field.
func ModifiedAtIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldModifiedAt, vs...))
}

// ModifiedAtNotIn applies the NotIn predicate on the "modified_at" field.
func ModifiedAtNotIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldModifiedAt, vs...))
}

// ModifiedAtGT applies the GT predicate on the "modified_at" field.
func ModifiedAtGT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldModifiedAt, v))
}

// ModifiedAtGTE applies the GTE predicate on the "modified_at" field.
func ModifiedAtGTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldModifiedAt, v))
}

// ModifiedAtLT applies the LT predicate on the "modified_at" field.
func ModifiedAtLT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldModifiedAt, v))
}

// ModifiedAtLTE applies the LTE predicate on the "modified_at" field.
func ModifiedAtLTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldModifiedAt, v))
}

// SourceSystemIDEQ applies the EQ predicate on the "source_system_id" field.
func SourceSystemIDEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldSourceSystemID, v))
}

// SourceSystemIDNEQ applies the NEQ predicate on the "source_system_id" field.
func SourceSystemIDNEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldSourceSystemID, v))
}

// SourceSystemIDIn applies the In predicate on the "source_system_id" field.
func SourceSystemIDIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldSourceSystemID, vs...))
}

// SourceSystemIDNotIn applies the NotIn predicate on the "source_system_id" field.
func SourceSystemIDNotIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldSourceSystemID, vs...))
}

// SourceSystemIDGT applies the GT predicate on the "source_system_id" field.
func SourceSystemIDGT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldSourceSystemID, v))
}

// SourceSystemIDGTE applies the GTE predicate on the "source_system_id" field.
func SourceSystemIDGTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldSourceSystemID, v))
}

// SourceSystemIDLT applies the LT predicate on the "source_system_id" field.
func SourceSystemIDLT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldSourceSystemID, v))
}

// SourceSystemIDLTE applies the LTE predicate on the "source_system_id" field.
func SourceSystemIDLTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldSourceSystemID, v))
}

// SourceSystemIDContains applies the Contains predicate on the "source_system_id" field.
func SourceSystemIDContains(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContains(FieldSourceSystemID, v))
}

// SourceSystemIDHasPrefix applies the HasPrefix predicate on the "source_system_id" field.
func SourceSystemIDHasPrefix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasPrefix(FieldSourceSystemID, v))
}

// SourceSystemIDHasSuffix applies the HasSuffix predicate on the "source_system_id" field.
func SourceSystemIDHasSuffix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasSuffix(FieldSourceSystemID, v))
}

// SourceSystemIDEqualFold applies the EqualFold predicate on the "source_system_id" field.
func SourceSystemIDEqualFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEqualFold(FieldSourceSystemID, v))
}

// SourceSystemIDContainsFold applies the ContainsFold predicate on the "source_system_id" field.
func SourceSystemIDContainsFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContainsFold(FieldSourceSystemID, v))
}

// ResourceEQ applies the EQ predicate on the "resource" field.
func ResourceEQ(v Resource) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldResource, v))
}

// ResourceNEQ applies the NEQ predicate on the "resource" field.
func ResourceNEQ(v Resource) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldResource, v))
}

// ResourceIn applies the In predicate on the "resource" field.
func ResourceIn(vs ...Resource) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldResource, vs...))
}

// ResourceNotIn applies the NotIn predicate on the "resource" field.
func ResourceNotIn(vs ...Resource) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldResource, vs...))
}

// RunTypeEQ applies the EQ predicate on the "run_type" field.
func RunTypeEQ(v RunType) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldRunType, v))
}

// RunTypeNEQ applies the NEQ predicate on the "run_type" field.
func RunTypeNEQ(v RunType) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldRunType, v))
}

// RunTypeIn applies the In predicate on the "run_type" field.
func RunTypeIn(vs ...RunType) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldRunType, vs...))
}

// RunTypeNotIn applies the NotIn predicate on the "run_type" field.
func RunTypeNotIn(vs ...RunType) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldRunType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// ProcessorVersionEQ applies the EQ predicate on the "processor_version" field.
func ProcessorVersionEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldProcessorVersion, v))
}

// ProcessorVersionNEQ applies the NEQ predicate on the "processor_version" field.
func ProcessorVersionNEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldProcessorVersion, v))
}

// ProcessorVersionIn applies the In predicate on the "processor_version" field.
func ProcessorVersionIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldProcessorVersion, vs...))
}

// ProcessorVersionNotIn applies the NotIn predicate on the "processor_version" field.
func ProcessorVersionNotIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldProcessorVersion, vs...))
}

// ProcessorVersionGT applies the GT predicate on the "processor_version" field.
func ProcessorVersionGT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldProcessorVersion, v))
}

// ProcessorVersionGTE applies the GTE predicate on the "processor_version" field.
func ProcessorVersionGTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldProcessorVersion, v))
}

// ProcessorVersionLT applies the LT predicate on the "processor_version" field.
func ProcessorVersionLT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldProcessorVersion, v))
}

// ProcessorVersionLTE applies the LTE predicate on the "processor_version" field.
func ProcessorVersionLTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldProcessorVersion, v))
}

// ProcessorVersionContains applies the Contains predicate on the "processor_version" field.
func ProcessorVersionContains(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContains(FieldProcessorVersion, v))
}

// ProcessorVersionHasPrefix applies the HasPrefix predicate on the "processor_version" field.
func ProcessorVersionHasPrefix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasPrefix(FieldProcessorVersion, v))
}

// ProcessorVersionHasSuffix applies the HasSuffix predicate on the "processor_version" field.
func ProcessorVersionHasSuffix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasSuffix(FieldProcessorVersion, v))
}

// ProcessorVersionEqualFold applies the EqualFold predicate on the "processor_version" field.
func ProcessorVersionEqualFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEqualFold(FieldProcessorVersion, v))
}

// ProcessorVersionContainsFold applies the ContainsFold predicate on the "processor_version" field.
func ProcessorVersionContainsFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContainsFold(FieldProcessorVersion, v))
}

// ReprocessOfEQ applies the EQ predicate on the "reprocess_of" field.
func ReprocessOfEQ(v uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldReprocessOf, v))
}

// ReprocessOfNEQ applies the NEQ predicate on the "reprocess_of" field.
func ReprocessOfNEQ(v uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldReprocessOf, v))
}

// ReprocessOfIn applies the In predicate on the "reprocess_of" field.
func ReprocessOfIn(vs ...uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldReprocessOf, vs...))
}

// ReprocessOfNotIn applies the NotIn predicate on the "reprocess_of" field.
func ReprocessOfNotIn(vs ...uuid.UUID) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldReprocessOf, vs...))
}

// ReprocessOfIsNil applies the IsNil predicate on the "reprocess_of" field.
func ReprocessOfIsNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIsNull(FieldReprocessOf))
}

// ReprocessOfNotNil applies the NotNil predicate on the "reprocess_of" field.
func ReprocessOfNotNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotNull(FieldReprocessOf))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotNull(FieldEndedAt))
}

// RecordCountEQ applies the EQ predicate on the "record_count" field.
func RecordCountEQ(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldRecordCount, v))
}

// RecordCountNEQ applies the NEQ predicate on the "record_count" field.
func RecordCountNEQ(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldRecordCount, v))
}

// RecordCountIn applies the In predicate on the "record_count" field.
func RecordCountIn(vs ...int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldRecordCount, vs...))
}

// RecordCountNotIn applies the NotIn predicate on the "record_count" field.
func RecordCountNotIn(vs ...int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldRecordCount, vs...))
}

// RecordCountGT applies the GT predicate on the "record_count" field.
func RecordCountGT(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldRecordCount, v))
}

// RecordCountGTE applies the GTE predicate on the "record_count" field.
func RecordCountGTE(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldRecordCount, v))
}

// RecordCountLT applies the LT predicate on the "record_count" field.
func RecordCountLT(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldRecordCount, v))
}

// RecordCountLTE applies the LTE predicate on the "record_count" field.
func RecordCountLTE(v int) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldRecordCount, v))
}

// HighWaterMarkEQ applies the EQ predicate on the "high_water_mark" field.
func HighWaterMarkEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldHighWaterMark, v))
}

// HighWaterMarkNEQ applies the NEQ predicate on the "high_water_mark" field.
func HighWaterMarkNEQ(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldHighWaterMark, v))
}

// HighWaterMarkIn applies the In predicate on the "high_water_mark" field.
func HighWaterMarkIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldHighWaterMark, vs...))
}

// HighWaterMarkNotIn applies the NotIn predicate on the "high_water_mark" field.
func HighWaterMarkNotIn(vs ...time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldHighWaterMark, vs...))
}

// HighWaterMarkGT applies the GT predicate on the "high_water_mark" field.
func HighWaterMarkGT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldHighWaterMark, v))
}

// HighWaterMarkGTE applies the GTE predicate on the "high_water_mark" field.
func HighWaterMarkGTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldHighWaterMark, v))
}

// HighWaterMarkLT applies the LT predicate on the "high_water_mark" field.
func HighWaterMarkLT(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldHighWaterMark, v))
}

// HighWaterMarkLTE applies the LTE predicate on the "high_water_mark" field.
func HighWaterMarkLTE(v time.Time) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldHighWaterMark, v))
}

// HighWaterMarkIsNil applies the IsNil predicate on the "high_water_mark" field.
func HighWaterMarkIsNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIsNull(FieldHighWaterMark))
}

// HighWaterMarkNotNil applies the NotNil predicate on the "high_water_mark" field.
func HighWaterMarkNotNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotNull(FieldHighWaterMark))
}

// ErrorSummaryEQ applies the EQ predicate on the "error_summary" field.
func ErrorSummaryEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEQ(FieldErrorSummary, v))
}

// ErrorSummaryNEQ applies the NEQ predicate on the "error_summary" field.
func ErrorSummaryNEQ(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNEQ(FieldErrorSummary, v))
}

// ErrorSummaryIn applies the In predicate on the "error_summary" field.
func ErrorSummaryIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIn(FieldErrorSummary, vs...))
}

// ErrorSummaryNotIn applies the NotIn predicate on the "error_summary" field.
func ErrorSummaryNotIn(vs ...string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotIn(FieldErrorSummary, vs...))
}

// ErrorSummaryGT applies the GT predicate on the "error_summary" field.
func ErrorSummaryGT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGT(FieldErrorSummary, v))
}

// ErrorSummaryGTE applies the GTE predicate on the "error_summary" field.
func ErrorSummaryGTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldGTE(FieldErrorSummary, v))
}

// ErrorSummaryLT applies the LT predicate on the "error_summary" field.
func ErrorSummaryLT(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLT(FieldErrorSummary, v))
}

// ErrorSummaryLTE applies the LTE predicate on the "error_summary" field.
func ErrorSummaryLTE(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldLTE(FieldErrorSummary, v))
}

// ErrorSummaryContains applies the Contains predicate on the "error_summary" field.
func ErrorSummaryContains(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContains(FieldErrorSummary, v))
}

// ErrorSummaryHasPrefix applies the HasPrefix predicate on the "error_summary" field.
func ErrorSummaryHasPrefix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasPrefix(FieldErrorSummary, v))
}

// ErrorSummaryHasSuffix applies the HasSuffix predicate on the "error_summary" field.
func ErrorSummaryHasSuffix(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldHasSuffix(FieldErrorSummary, v))
}

// ErrorSummaryIsNil applies the IsNil predicate on the "error_summary" field.
func ErrorSummaryIsNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIsNull(FieldErrorSummary))
}

// ErrorSummaryNotNil applies the NotNil predicate on the "error_summary" field.
func ErrorSummaryNotNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotNull(FieldErrorSummary))
}

// ErrorSummaryEqualFold applies the EqualFold predicate on the "error_summary" field.
func ErrorSummaryEqualFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldEqualFold(FieldErrorSummary, v))
}

// ErrorSummaryContainsFold applies the ContainsFold predicate on the "error_summary" field.
func ErrorSummaryContainsFold(v string) predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldContainsFold(FieldErrorSummary, v))
}

// LogsIsNil applies the IsNil predicate on the "logs" field.
func LogsIsNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldIsNull(FieldLogs))
}

// LogsNotNil applies the NotNil predicate on the "logs" field.
func LogsNotNil() predicate.SyncEvent {
	return predicate.SyncEvent(sql.FieldNotNull(FieldLogs))
}

// HasSourceSystem applies the HasEdge predicate on the "source_system" edge.
func HasSourceSystem() predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceSystemTable, SourceSystemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceSystemWith applies the HasEdge predicate on the "source_system" edge with a given conditions (other predicates).
func HasSourceSystemWith(preds ...predicate.SourceSystem) predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := newSourceSystemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRawOutputs applies the HasEdge predicate on the "raw_outputs" edge.
func HasRawOutputs() predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RawOutputsTable, RawOutputsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRawOutputsWith applies the HasEdge predicate on the "raw_outputs" edge with a given conditions (other predicates).
func HasRawOutputsWith(preds ...predicate.RawOutput) predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := newRawOutputsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachmentJobs applies the HasEdge predicate on the "attachment_jobs" edge.
func HasAttachmentJobs() predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentJobsTable, AttachmentJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentJobsWith applies the HasEdge predicate on the "attachment_jobs" edge with a given conditions (other predicates).
func HasAttachmentJobsWith(preds ...predicate.AttachmentJob) predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := newAttachmentJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOriginalSync applies the HasEdge predicate on the "original_sync" edge.
func HasOriginalSync() predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OriginalSyncTable, OriginalSyncColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOriginalSyncWith applies the HasEdge predicate on the "original_sync" edge with a given conditions (other predicates).
func HasOriginalSyncWith(preds ...predicate.SyncEvent) predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := newOriginalSyncStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReprocesses applies the HasEdge predicate on the "reprocesses" edge.
func HasReprocesses() predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReprocessesTable, ReprocessesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReprocessesWith applies the HasEdge predicate on the "reprocesses" edge with a given conditions (other predicates).
func HasReprocessesWith(preds ...predicate.SyncEvent) predicate.SyncEvent {
	return predicate.SyncEvent(func(s *sql.Selector) {
		step := newReprocessesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncEvent) predicate.SyncEvent {
	return predicate.SyncEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncEvent) predicate.SyncEvent {
	return predicate.SyncEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncEvent) predicate.SyncEvent {
	return predicate.SyncEvent(sql.NotPredicates(p))
}
