// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/attachment"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/attachmentjob"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/media"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/rawoutput"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/syncevent"
	"github.com/google/uuid"
)

// AttachmentJobCreate is the builder for creating a AttachmentJob entity.
type AttachmentJobCreate struct {
	config
	mutation *AttachmentJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AttachmentJobCreate) SetCreatedAt(v time.Time) *AttachmentJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableCreatedAt(v *time.Time) *AttachmentJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *AttachmentJobCreate) SetModifiedAt(v time.Time) *AttachmentJobCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableModifiedAt(v *time.Time) *AttachmentJobCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetMediaKey sets the "media_key" field.
func (_c *AttachmentJobCreate) SetMediaKey(v string) *AttachmentJobCreate {
	_c.mutation.SetMediaKey(v)
	return _c
}

// SetSyncEventID sets the "sync_event_id" field.
func (_c *AttachmentJobCreate) SetSyncEventID(v uuid.UUID) *AttachmentJobCreate {
	_c.mutation.SetSyncEventID(v)
	return _c
}

// SetRawOutputID sets the "raw_output_id" field.
func (_c *AttachmentJobCreate) SetRawOutputID(v uuid.UUID) *AttachmentJobCreate {
	_c.mutation.SetRawOutputID(v)
	return _c
}

// SetNillableRawOutputID sets the "raw_output_id" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableRawOutputID(v *uuid.UUID) *AttachmentJobCreate {
	if v != nil {
		_c.SetRawOutputID(*v)
	}
	return _c
}

// SetAttachmentID sets the "attachment_id" field.
func (_c *AttachmentJobCreate) SetAttachmentID(v uuid.UUID) *AttachmentJobCreate {
	_c.mutation.SetAttachmentID(v)
	return _c
}

// SetNillableAttachmentID sets the "attachment_id" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableAttachmentID(v *uuid.UUID) *AttachmentJobCreate {
	if v != nil {
		_c.SetAttachmentID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AttachmentJobCreate) SetStatus(v attachmentjob.Status) *AttachmentJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableStatus(v *attachmentjob.Status) *AttachmentJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *AttachmentJobCreate) SetAttemptCount(v int) *AttachmentJobCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableAttemptCount(v *int) *AttachmentJobCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *AttachmentJobCreate) SetLastError(v string) *AttachmentJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableLastError(v *string) *AttachmentJobCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *AttachmentJobCreate) SetNextRetryAt(v time.Time) *AttachmentJobCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableNextRetryAt(v *time.Time) *AttachmentJobCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *AttachmentJobCreate) SetClaimedAt(v time.Time) *AttachmentJobCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableClaimedAt(v *time.Time) *AttachmentJobCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetClaimedBy sets the "claimed_by" field.
func (_c *AttachmentJobCreate) SetClaimedBy(v string) *AttachmentJobCreate {
	_c.mutation.SetClaimedBy(v)
	return _c
}

// SetNillableClaimedBy sets the "claimed_by" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableClaimedBy(v *string) *AttachmentJobCreate {
	if v != nil {
		_c.SetClaimedBy(*v)
	}
	return _c
}

// SetMediaModifiedAt sets the "media_modified_at" field.
func (_c *AttachmentJobCreate) SetMediaModifiedAt(v time.Time) *AttachmentJobCreate {
	_c.mutation.SetMediaModifiedAt(v)
	return _c
}

// SetNillableMediaModifiedAt sets the "media_modified_at" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableMediaModifiedAt(v *time.Time) *AttachmentJobCreate {
	if v != nil {
		_c.SetMediaModifiedAt(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *AttachmentJobCreate) SetMimeType(v string) *AttachmentJobCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableMimeType(v *string) *AttachmentJobCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *AttachmentJobCreate) SetSizeBytes(v int) *AttachmentJobCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableSizeBytes(v *int) *AttachmentJobCreate {
	if v != nil {
		_c.SetSizeBytes(*v)
	}
	return _c
}

// SetLogs sets the "logs" field.
func (_c *AttachmentJobCreate) SetLogs(v []string) *AttachmentJobCreate {
	_c.mutation.SetLogs(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AttachmentJobCreate) SetID(v uuid.UUID) *AttachmentJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AttachmentJobCreate) SetNillableID(v *uuid.UUID) *AttachmentJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetMediaID sets the "media" edge to the Media entity by ID.
func (_c *AttachmentJobCreate) SetMediaID(id string) *AttachmentJobCreate {
	_c.mutation.SetMediaID(id)
	return _c
}

// SetMedia sets the "media" edge to the Media entity.
func (_c *AttachmentJobCreate) SetMedia(v *Media) *AttachmentJobCreate {
	return _c.SetMediaID(v.ID)
}

// SetSyncEvent sets the "sync_event" edge to the SyncEvent entity.
func (_c *AttachmentJobCreate) SetSyncEvent(v *SyncEvent) *AttachmentJobCreate {
	return _c.SetSyncEventID(v.ID)
}

// SetRawOutput sets the "raw_output" edge to the RawOutput entity.
func (_c *AttachmentJobCreate) SetRawOutput(v *RawOutput) *AttachmentJobCreate {
	return _c.SetRawOutputID(v.ID)
}

// SetAttachment sets the "attachment" edge to the Attachment entity.
func (_c *AttachmentJobCreate) SetAttachment(v *Attachment) *AttachmentJobCreate {
	return _c.SetAttachmentID(v.ID)
}

// Mutation returns the AttachmentJobMutation object of the builder.
func (_c *AttachmentJobCreate) Mutation() *AttachmentJobMutation {
	return _c.mutation
}

// Save creates the AttachmentJob in the database.
func (_c *AttachmentJobCreate) Save(ctx context.Context) (*AttachmentJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttachmentJobCreate) SaveX(ctx context.Context) *AttachmentJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttachmentJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := attachmentjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		v := attachmentjob.DefaultModifiedAt()
		_c.mutation.SetModifiedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := attachmentjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := attachmentjob.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := attachmentjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttachmentJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AttachmentJob.created_at"`)}
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New(`ent: missing required field "AttachmentJob.modified_at"`)}
	}
	if _, ok := _c.mutation.MediaKey(); !ok {
		return &ValidationError{Name: "media_key", err: errors.New(`ent: missing required field "AttachmentJob.media_key"`)}
	}
	if _, ok := _c.mutation.SyncEventID(); !ok {
		return &ValidationError{Name: "sync_event_id", err: errors.New(`ent: missing required field "AttachmentJob.sync_event_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AttachmentJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := attachmentjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AttachmentJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "AttachmentJob.attempt_count"`)}
	}
	if len(_c.mutation.MediaIDs()) == 0 {
		return &ValidationError{Name: "media", err: errors.New(`ent: missing required edge "AttachmentJob.media"`)}
	}
	if len(_c.mutation.SyncEventIDs()) == 0 {
		return &ValidationError{Name: "sync_event", err: errors.New(`ent: missing required edge "AttachmentJob.sync_event"`)}
	}
	return nil
}

func (_c *AttachmentJobCreate) sqlSave(ctx context.Context) (*AttachmentJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttachmentJobCreate) createSpec() (*AttachmentJob, *sqlgraph.CreateSpec) {
	var (
		_node = &AttachmentJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attachmentjob.Table, sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(attachmentjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(attachmentjob.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(attachmentjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(attachmentjob.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(attachmentjob.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(attachmentjob.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(attachmentjob.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = &value
	}
	if value, ok := _c.mutation.ClaimedBy(); ok {
		_spec.SetField(attachmentjob.FieldClaimedBy, field.TypeString, value)
		_node.ClaimedBy = &value
	}
	if value, ok := _c.mutation.MediaModifiedAt(); ok {
		_spec.SetField(attachmentjob.FieldMediaModifiedAt, field.TypeTime, value)
		_node.MediaModifiedAt = &value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(attachmentjob.FieldMimeType, field.TypeString, value)
		_node.MimeType = &value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(attachmentjob.FieldSizeBytes, field.TypeInt, value)
		_node.SizeBytes = &value
	}
	if value, ok := _c.mutation.Logs(); ok {
		_spec.SetField(attachmentjob.FieldLogs, field.TypeJSON, value)
		_node.Logs = value
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachmentjob.MediaTable,
			Columns: []string{attachmentjob.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MediaKey = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SyncEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachmentjob.SyncEventTable,
			Columns: []string{attachmentjob.SyncEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SyncEventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RawOutputIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachmentjob.RawOutputTable,
			Columns: []string{attachmentjob.RawOutputColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RawOutputID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachmentjob.AttachmentTable,
			Columns: []string{attachmentjob.AttachmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AttachmentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AttachmentJob.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AttachmentJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AttachmentJobCreate) OnConflict(opts ...sql.ConflictOption) *AttachmentJobUpsertOne {
	_c.conflict = opts
	return &AttachmentJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AttachmentJobCreate) OnConflictColumns(columns ...string) *AttachmentJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AttachmentJobUpsertOne{
		create: _c,
	}
}

type (
	// AttachmentJobUpsertOne is the builder for "upsert"-ing
	//  one AttachmentJob node.
	AttachmentJobUpsertOne struct {
		create *AttachmentJobCreate
	}

	// AttachmentJobUpsert is the "OnConflict" setter.
	AttachmentJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetModifiedAt sets the "modified_at" field.
func (u *AttachmentJobUpsert) SetModifiedAt(v time.Time) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateModifiedAt() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldModifiedAt)
	return u
}

// SetMediaKey sets the "media_key" field.
func (u *AttachmentJobUpsert) SetMediaKey(v string) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldMediaKey, v)
	return u
}

// UpdateMediaKey sets the "media_key" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateMediaKey() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldMediaKey)
	return u
}

// SetSyncEventID sets the "sync_event_id" field.
func (u *AttachmentJobUpsert) SetSyncEventID(v uuid.UUID) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldSyncEventID, v)
	return u
}

// UpdateSyncEventID sets the "sync_event_id" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateSyncEventID() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldSyncEventID)
	return u
}

// SetRawOutputID sets the "raw_output_id" field.
func (u *AttachmentJobUpsert) SetRawOutputID(v uuid.UUID) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldRawOutputID, v)
	return u
}

// UpdateRawOutputID sets the "raw_output_id" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateRawOutputID() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldRawOutputID)
	return u
}

// ClearRawOutputID clears the value of the "raw_output_id" field.
func (u *AttachmentJobUpsert) ClearRawOutputID() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldRawOutputID)
	return u
}

// SetAttachmentID sets the "attachment_id" field.
func (u *AttachmentJobUpsert) SetAttachmentID(v uuid.UUID) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldAttachmentID, v)
	return u
}

// UpdateAttachmentID sets the "attachment_id" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateAttachmentID() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldAttachmentID)
	return u
}

// ClearAttachmentID clears the value of the "attachment_id" field.
func (u *AttachmentJobUpsert) ClearAttachmentID() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldAttachmentID)
	return u
}

// SetStatus sets the "status" field.
func (u *AttachmentJobUpsert) SetStatus(v attachmentjob.Status) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateStatus() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldStatus)
	return u
}

// SetAttemptCount sets the "attempt_count" field.
func (u *AttachmentJobUpsert) SetAttemptCount(v int) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldAttemptCount, v)
	return u
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateAttemptCount() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldAttemptCount)
	return u
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *AttachmentJobUpsert) AddAttemptCount(v int) *AttachmentJobUpsert {
	u.Add(attachmentjob.FieldAttemptCount, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *AttachmentJobUpsert) SetLastError(v string) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateLastError() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *AttachmentJobUpsert) ClearLastError() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldLastError)
	return u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *AttachmentJobUpsert) SetNextRetryAt(v time.Time) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldNextRetryAt, v)
	return u
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateNextRetryAt() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldNextRetryAt)
	return u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *AttachmentJobUpsert) ClearNextRetryAt() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldNextRetryAt)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *AttachmentJobUpsert) SetClaimedAt(v time.Time) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateClaimedAt() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldClaimedAt)
	return u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *AttachmentJobUpsert) ClearClaimedAt() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldClaimedAt)
	return u
}

// SetClaimedBy sets the "claimed_by" field.
func (u *AttachmentJobUpsert) SetClaimedBy(v string) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldClaimedBy, v)
	return u
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateClaimedBy() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldClaimedBy)
	return u
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *AttachmentJobUpsert) ClearClaimedBy() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldClaimedBy)
	return u
}

// SetMediaModifiedAt sets the "media_modified_at" field.
func (u *AttachmentJobUpsert) SetMediaModifiedAt(v time.Time) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldMediaModifiedAt, v)
	return u
}

// UpdateMediaModifiedAt sets the "media_modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateMediaModifiedAt() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldMediaModifiedAt)
	return u
}

// ClearMediaModifiedAt clears the value of the "media_modified_at" field.
func (u *AttachmentJobUpsert) ClearMediaModifiedAt() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldMediaModifiedAt)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *AttachmentJobUpsert) SetMimeType(v string) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateMimeType() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldMimeType)
	return u
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AttachmentJobUpsert) ClearMimeType() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldMimeType)
	return u
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AttachmentJobUpsert) SetSizeBytes(v int) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldSizeBytes, v)
	return u
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateSizeBytes() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldSizeBytes)
	return u
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AttachmentJobUpsert) AddSizeBytes(v int) *AttachmentJobUpsert {
	u.Add(attachmentjob.FieldSizeBytes, v)
	return u
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *AttachmentJobUpsert) ClearSizeBytes() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldSizeBytes)
	return u
}

// SetLogs sets the "logs" field.
func (u *AttachmentJobUpsert) SetLogs(v []string) *AttachmentJobUpsert {
	u.Set(attachmentjob.FieldLogs, v)
	return u
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *AttachmentJobUpsert) UpdateLogs() *AttachmentJobUpsert {
	u.SetExcluded(attachmentjob.FieldLogs)
	return u
}

// ClearLogs clears the value of the "logs" field.
func (u *AttachmentJobUpsert) ClearLogs() *AttachmentJobUpsert {
	u.SetNull(attachmentjob.FieldLogs)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(attachmentjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AttachmentJobUpsertOne) UpdateNewValues() *AttachmentJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(attachmentjob.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(attachmentjob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AttachmentJobUpsertOne) Ignore() *AttachmentJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AttachmentJobUpsertOne) DoNothing() *AttachmentJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AttachmentJobCreate.OnConflict
// documentation for more info.
func (u *AttachmentJobUpsertOne) Update(set func(*AttachmentJobUpsert)) *AttachmentJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AttachmentJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *AttachmentJobUpsertOne) SetModifiedAt(v time.Time) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateModifiedAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetMediaKey sets the "media_key" field.
func (u *AttachmentJobUpsertOne) SetMediaKey(v string) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMediaKey(v)
	})
}

// UpdateMediaKey sets the "media_key" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateMediaKey() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMediaKey()
	})
}

// SetSyncEventID sets the "sync_event_id" field.
func (u *AttachmentJobUpsertOne) SetSyncEventID(v uuid.UUID) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetSyncEventID(v)
	})
}

// UpdateSyncEventID sets the "sync_event_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateSyncEventID() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateSyncEventID()
	})
}

// SetRawOutputID sets the "raw_output_id" field.
func (u *AttachmentJobUpsertOne) SetRawOutputID(v uuid.UUID) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetRawOutputID(v)
	})
}

// UpdateRawOutputID sets the "raw_output_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateRawOutputID() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateRawOutputID()
	})
}

// ClearRawOutputID clears the value of the "raw_output_id" field.
func (u *AttachmentJobUpsertOne) ClearRawOutputID() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearRawOutputID()
	})
}

// SetAttachmentID sets the "attachment_id" field.
func (u *AttachmentJobUpsertOne) SetAttachmentID(v uuid.UUID) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetAttachmentID(v)
	})
}

// UpdateAttachmentID sets the "attachment_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateAttachmentID() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateAttachmentID()
	})
}

// ClearAttachmentID clears the value of the "attachment_id" field.
func (u *AttachmentJobUpsertOne) ClearAttachmentID() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearAttachmentID()
	})
}

// SetStatus sets the "status" field.
func (u *AttachmentJobUpsertOne) SetStatus(v attachmentjob.Status) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateStatus() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateStatus()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *AttachmentJobUpsertOne) SetAttemptCount(v int) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *AttachmentJobUpsertOne) AddAttemptCount(v int) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateAttemptCount() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *AttachmentJobUpsertOne) SetLastError(v string) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateLastError() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *AttachmentJobUpsertOne) ClearLastError() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *AttachmentJobUpsertOne) SetNextRetryAt(v time.Time) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateNextRetryAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *AttachmentJobUpsertOne) ClearNextRetryAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *AttachmentJobUpsertOne) SetClaimedAt(v time.Time) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateClaimedAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *AttachmentJobUpsertOne) ClearClaimedAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearClaimedAt()
	})
}

// SetClaimedBy sets the "claimed_by" field.
func (u *AttachmentJobUpsertOne) SetClaimedBy(v string) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetClaimedBy(v)
	})
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateClaimedBy() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateClaimedBy()
	})
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *AttachmentJobUpsertOne) ClearClaimedBy() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearClaimedBy()
	})
}

// SetMediaModifiedAt sets the "media_modified_at" field.
func (u *AttachmentJobUpsertOne) SetMediaModifiedAt(v time.Time) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMediaModifiedAt(v)
	})
}

// UpdateMediaModifiedAt sets the "media_modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateMediaModifiedAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMediaModifiedAt()
	})
}

// ClearMediaModifiedAt clears the value of the "media_modified_at" field.
func (u *AttachmentJobUpsertOne) ClearMediaModifiedAt() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearMediaModifiedAt()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AttachmentJobUpsertOne) SetMimeType(v string) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateMimeType() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AttachmentJobUpsertOne) ClearMimeType() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AttachmentJobUpsertOne) SetSizeBytes(v int) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AttachmentJobUpsertOne) AddSizeBytes(v int) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateSizeBytes() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateSizeBytes()
	})
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *AttachmentJobUpsertOne) ClearSizeBytes() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearSizeBytes()
	})
}

// SetLogs sets the "logs" field.
func (u *AttachmentJobUpsertOne) SetLogs(v []string) *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetLogs(v)
	})
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *AttachmentJobUpsertOne) UpdateLogs() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateLogs()
	})
}

// ClearLogs clears the value of the "logs" field.
func (u *AttachmentJobUpsertOne) ClearLogs() *AttachmentJobUpsertOne {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearLogs()
	})
}

// Exec executes the query.
func (u *AttachmentJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AttachmentJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AttachmentJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AttachmentJobUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AttachmentJobUpsertOne.ID is not supported by MySQL driver. Use AttachmentJobUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AttachmentJobUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AttachmentJobCreateBulk is the builder for creating many AttachmentJob entities in bulk.
type AttachmentJobCreateBulk struct {
	config
	err      error
	builders []*AttachmentJobCreate
	conflict []sql.ConflictOption
}

// Save creates the AttachmentJob entities in the database.
func (_c *AttachmentJobCreateBulk) Save(ctx context.Context) ([]*AttachmentJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AttachmentJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttachmentJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttachmentJobCreateBulk) SaveX(ctx context.Context) []*AttachmentJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AttachmentJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AttachmentJobUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AttachmentJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *AttachmentJobUpsertBulk {
	_c.conflict = opts
	return &AttachmentJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AttachmentJobCreateBulk) OnConflictColumns(columns ...string) *AttachmentJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AttachmentJobUpsertBulk{
		create: _c,
	}
}

// AttachmentJobUpsertBulk is the builder for "upsert"-ing
// a bulk of AttachmentJob nodes.
type AttachmentJobUpsertBulk struct {
	create *AttachmentJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(attachmentjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AttachmentJobUpsertBulk) UpdateNewValues() *AttachmentJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(attachmentjob.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(attachmentjob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AttachmentJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AttachmentJobUpsertBulk) Ignore() *AttachmentJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AttachmentJobUpsertBulk) DoNothing() *AttachmentJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AttachmentJobCreateBulk.OnConflict
// documentation for more info.
func (u *AttachmentJobUpsertBulk) Update(set func(*AttachmentJobUpsert)) *AttachmentJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AttachmentJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *AttachmentJobUpsertBulk) SetModifiedAt(v time.Time) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateModifiedAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetMediaKey sets the "media_key" field.
func (u *AttachmentJobUpsertBulk) SetMediaKey(v string) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMediaKey(v)
	})
}

// UpdateMediaKey sets the "media_key" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateMediaKey() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMediaKey()
	})
}

// SetSyncEventID sets the "sync_event_id" field.
func (u *AttachmentJobUpsertBulk) SetSyncEventID(v uuid.UUID) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetSyncEventID(v)
	})
}

// UpdateSyncEventID sets the "sync_event_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateSyncEventID() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateSyncEventID()
	})
}

// SetRawOutputID sets the "raw_output_id" field.
func (u *AttachmentJobUpsertBulk) SetRawOutputID(v uuid.UUID) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetRawOutputID(v)
	})
}

// UpdateRawOutputID sets the "raw_output_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateRawOutputID() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateRawOutputID()
	})
}

// ClearRawOutputID clears the value of the "raw_output_id" field.
func (u *AttachmentJobUpsertBulk) ClearRawOutputID() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearRawOutputID()
	})
}

// SetAttachmentID sets the "attachment_id" field.
func (u *AttachmentJobUpsertBulk) SetAttachmentID(v uuid.UUID) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetAttachmentID(v)
	})
}

// UpdateAttachmentID sets the "attachment_id" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateAttachmentID() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateAttachmentID()
	})
}

// ClearAttachmentID clears the value of the "attachment_id" field.
func (u *AttachmentJobUpsertBulk) ClearAttachmentID() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearAttachmentID()
	})
}

// SetStatus sets the "status" field.
func (u *AttachmentJobUpsertBulk) SetStatus(v attachmentjob.Status) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateStatus() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateStatus()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *AttachmentJobUpsertBulk) SetAttemptCount(v int) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *AttachmentJobUpsertBulk) AddAttemptCount(v int) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateAttemptCount() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetLastError sets the "last_error" field.
func (u *AttachmentJobUpsertBulk) SetLastError(v string) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateLastError() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *AttachmentJobUpsertBulk) ClearLastError() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *AttachmentJobUpsertBulk) SetNextRetryAt(v time.Time) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateNextRetryAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *AttachmentJobUpsertBulk) ClearNextRetryAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *AttachmentJobUpsertBulk) SetClaimedAt(v time.Time) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateClaimedAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateClaimedAt()
	})
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (u *AttachmentJobUpsertBulk) ClearClaimedAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearClaimedAt()
	})
}

// SetClaimedBy sets the "claimed_by" field.
func (u *AttachmentJobUpsertBulk) SetClaimedBy(v string) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetClaimedBy(v)
	})
}

// UpdateClaimedBy sets the "claimed_by" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateClaimedBy() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateClaimedBy()
	})
}

// ClearClaimedBy clears the value of the "claimed_by" field.
func (u *AttachmentJobUpsertBulk) ClearClaimedBy() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearClaimedBy()
	})
}

// SetMediaModifiedAt sets the "media_modified_at" field.
func (u *AttachmentJobUpsertBulk) SetMediaModifiedAt(v time.Time) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMediaModifiedAt(v)
	})
}

// UpdateMediaModifiedAt sets the "media_modified_at" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateMediaModifiedAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMediaModifiedAt()
	})
}

// ClearMediaModifiedAt clears the value of the "media_modified_at" field.
func (u *AttachmentJobUpsertBulk) ClearMediaModifiedAt() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearMediaModifiedAt()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *AttachmentJobUpsertBulk) SetMimeType(v string) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateMimeType() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateMimeType()
	})
}

// ClearMimeType clears the value of the "mime_type" field.
func (u *AttachmentJobUpsertBulk) ClearMimeType() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearMimeType()
	})
}

// SetSizeBytes sets the "size_bytes" field.
func (u *AttachmentJobUpsertBulk) SetSizeBytes(v int) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetSizeBytes(v)
	})
}

// AddSizeBytes adds v to the "size_bytes" field.
func (u *AttachmentJobUpsertBulk) AddSizeBytes(v int) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.AddSizeBytes(v)
	})
}

// UpdateSizeBytes sets the "size_bytes" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateSizeBytes() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateSizeBytes()
	})
}

// ClearSizeBytes clears the value of the "size_bytes" field.
func (u *AttachmentJobUpsertBulk) ClearSizeBytes() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearSizeBytes()
	})
}

// SetLogs sets the "logs" field.
func (u *AttachmentJobUpsertBulk) SetLogs(v []string) *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.SetLogs(v)
	})
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *AttachmentJobUpsertBulk) UpdateLogs() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.UpdateLogs()
	})
}

// ClearLogs clears the value of the "logs" field.
func (u *AttachmentJobUpsertBulk) ClearLogs() *AttachmentJobUpsertBulk {
	return u.Update(func(s *AttachmentJobUpsert) {
		s.ClearLogs()
	})
}

// Exec executes the query.
func (u *AttachmentJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AttachmentJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AttachmentJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AttachmentJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
