// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/attachment"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/attachmentjob"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/media"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/rawoutput"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/syncevent"
)

// AttachmentJob is the model entity for the AttachmentJob schema.
type AttachmentJob struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ModifiedAt holds the value of the "modified_at" field.
	ModifiedAt time.Time `json:"modified_at,omitempty"`
	// MediaKey holds the value of the "media_key" field.
	MediaKey string `json:"media_key,omitempty"`
	// SyncEventID holds the value of the "sync_event_id" field.
	SyncEventID uuid.UUID `json:"sync_event_id,omitempty"`
	// RawOutputID holds the value of the "raw_output_id" field.
	RawOutputID *uuid.UUID `json:"raw_output_id,omitempty"`
	// Set when status reaches Succeeded
	AttachmentID *uuid.UUID `json:"attachment_id,omitempty"`
	// Status holds the value of the "status" field.
	Status attachmentjob.Status `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// NextRetryAt holds the value of the "next_retry_at" field.
	NextRetryAt *time.Time `json:"next_retry_at,omitempty"`
	// When a worker claimed this job. Cleared when status returns to pending.
	ClaimedAt *time.Time `json:"claimed_at,omitempty"`
	// Worker identity (hostname+pid or per-process UUID). Cleared on requeue.
	ClaimedBy *string `json:"claimed_by,omitempty"`
	// MediaModificationTimestamp the job was enqueued for. Used to gate re-enqueue on content change.
	MediaModifiedAt *time.Time `json:"media_modified_at,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType *string `json:"mime_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes *int `json:"size_bytes,omitempty"`
	// Logs holds the value of the "logs" field.
	Logs []string `json:"logs,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttachmentJobQuery when eager-loading is set.
	Edges        AttachmentJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttachmentJobEdges holds the relations/edges for other nodes in the graph.
type AttachmentJobEdges struct {
	// Media holds the value of the media edge.
	Media *Media `json:"media,omitempty"`
	// SyncEvent holds the value of the sync_event edge.
	SyncEvent *SyncEvent `json:"sync_event,omitempty"`
	// RawOutput holds the value of the raw_output edge.
	RawOutput *RawOutput `json:"raw_output,omitempty"`
	// Attachment holds the value of the attachment edge.
	Attachment *Attachment `json:"attachment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// MediaOrErr returns the Media value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttachmentJobEdges) MediaOrErr() (*Media, error) {
	if e.Media != nil {
		return e.Media, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: media.Label}
	}
	return nil, &NotLoadedError{edge: "media"}
}

// SyncEventOrErr returns the SyncEvent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttachmentJobEdges) SyncEventOrErr() (*SyncEvent, error) {
	if e.SyncEvent != nil {
		return e.SyncEvent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: syncevent.Label}
	}
	return nil, &NotLoadedError{edge: "sync_event"}
}

// RawOutputOrErr returns the RawOutput value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttachmentJobEdges) RawOutputOrErr() (*RawOutput, error) {
	if e.RawOutput != nil {
		return e.RawOutput, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: rawoutput.Label}
	}
	return nil, &NotLoadedError{edge: "raw_output"}
}

// AttachmentOrErr returns the Attachment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttachmentJobEdges) AttachmentOrErr() (*Attachment, error) {
	if e.Attachment != nil {
		return e.Attachment, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: attachment.Label}
	}
	return nil, &NotLoadedError{edge: "attachment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttachmentJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attachmentjob.FieldRawOutputID, attachmentjob.FieldAttachmentID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case attachmentjob.FieldLogs:
			values[i] = new([]byte)
		case attachmentjob.FieldAttemptCount, attachmentjob.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case attachmentjob.FieldMediaKey, attachmentjob.FieldStatus, attachmentjob.FieldLastError, attachmentjob.FieldClaimedBy, attachmentjob.FieldMimeType:
			values[i] = new(sql.NullString)
		case attachmentjob.FieldCreatedAt, attachmentjob.FieldModifiedAt, attachmentjob.FieldNextRetryAt, attachmentjob.FieldClaimedAt, attachmentjob.FieldMediaModifiedAt:
			values[i] = new(sql.NullTime)
		case attachmentjob.FieldID, attachmentjob.FieldSyncEventID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttachmentJob fields.
func (_m *AttachmentJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attachmentjob.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case attachmentjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case attachmentjob.FieldModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified_at", values[i])
			} else if value.Valid {
				_m.ModifiedAt = value.Time
			}
		case attachmentjob.FieldMediaKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_key", values[i])
			} else if value.Valid {
				_m.MediaKey = value.String
			}
		case attachmentjob.FieldSyncEventID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field sync_event_id", values[i])
			} else if value != nil {
				_m.SyncEventID = *value
			}
		case attachmentjob.FieldRawOutputID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field raw_output_id", values[i])
			} else if value.Valid {
				_m.RawOutputID = new(uuid.UUID)
				*_m.RawOutputID = *value.S.(*uuid.UUID)
			}
		case attachmentjob.FieldAttachmentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field attachment_id", values[i])
			} else if value.Valid {
				_m.AttachmentID = new(uuid.UUID)
				*_m.AttachmentID = *value.S.(*uuid.UUID)
			}
		case attachmentjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = attachmentjob.Status(value.String)
			}
		case attachmentjob.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case attachmentjob.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case attachmentjob.FieldNextRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_retry_at", values[i])
			} else if value.Valid {
				_m.NextRetryAt = new(time.Time)
				*_m.NextRetryAt = value.Time
			}
		case attachmentjob.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = new(time.Time)
				*_m.ClaimedAt = value.Time
			}
		case attachmentjob.FieldClaimedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_by", values[i])
			} else if value.Valid {
				_m.ClaimedBy = new(string)
				*_m.ClaimedBy = value.String
			}
		case attachmentjob.FieldMediaModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field media_modified_at", values[i])
			} else if value.Valid {
				_m.MediaModifiedAt = new(time.Time)
				*_m.MediaModifiedAt = value.Time
			}
		case attachmentjob.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = new(string)
				*_m.MimeType = value.String
			}
		case attachmentjob.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = new(int)
				*_m.SizeBytes = int(value.Int64)
			}
		case attachmentjob.FieldLogs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field logs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Logs); err != nil {
					return fmt.Errorf("unmarshal field logs: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AttachmentJob.
// This includes values selected through modifiers, order, etc.
func (_m *AttachmentJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMedia queries the "media" edge of the AttachmentJob entity.
func (_m *AttachmentJob) QueryMedia() *MediaQuery {
	return NewAttachmentJobClient(_m.config).QueryMedia(_m)
}

// QuerySyncEvent queries the "sync_event" edge of the AttachmentJob entity.
func (_m *AttachmentJob) QuerySyncEvent() *SyncEventQuery {
	return NewAttachmentJobClient(_m.config).QuerySyncEvent(_m)
}

// QueryRawOutput queries the "raw_output" edge of the AttachmentJob entity.
func (_m *AttachmentJob) QueryRawOutput() *RawOutputQuery {
	return NewAttachmentJobClient(_m.config).QueryRawOutput(_m)
}

// QueryAttachment queries the "attachment" edge of the AttachmentJob entity.
func (_m *AttachmentJob) QueryAttachment() *AttachmentQuery {
	return NewAttachmentJobClient(_m.config).QueryAttachment(_m)
}

// Update returns a builder for updating this AttachmentJob.
// Note that you need to call AttachmentJob.Unwrap() before calling this method if this AttachmentJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AttachmentJob) Update() *AttachmentJobUpdateOne {
	return NewAttachmentJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AttachmentJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AttachmentJob) Unwrap() *AttachmentJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttachmentJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AttachmentJob) String() string {
	var builder strings.Builder
	builder.WriteString("AttachmentJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("modified_at=")
	builder.WriteString(_m.ModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("media_key=")
	builder.WriteString(_m.MediaKey)
	builder.WriteString(", ")
	builder.WriteString("sync_event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncEventID))
	builder.WriteString(", ")
	if v := _m.RawOutputID; v != nil {
		builder.WriteString("raw_output_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AttachmentID; v != nil {
		builder.WriteString("attachment_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NextRetryAt; v != nil {
		builder.WriteString("next_retry_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClaimedAt; v != nil {
		builder.WriteString("claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClaimedBy; v != nil {
		builder.WriteString("claimed_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MediaModifiedAt; v != nil {
		builder.WriteString("media_modified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MimeType; v != nil {
		builder.WriteString("mime_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SizeBytes; v != nil {
		builder.WriteString("size_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("logs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Logs))
	builder.WriteByte(')')
	return builder.String()
}

// AttachmentJobs is a parsable slice of AttachmentJob.
type AttachmentJobs []*AttachmentJob
