// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Office) MainOffice(ctx context.Context) (*Office, error) {
	result, err := _m.Edges.MainOfficeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryMainOffice().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Office) Branches(ctx context.Context) (result []*Office, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedBranches(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.BranchesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryBranches().All(ctx)
	}
	return result, err
}

func (_m *OpenHouse) Property(ctx context.Context) (*Property, error) {
	result, err := _m.Edges.PropertyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProperty().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Property) Rooms(ctx context.Context) (result []*PropertyRoom, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRooms(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RoomsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRooms().All(ctx)
	}
	return result, err
}

func (_m *Property) UnitTypes(ctx context.Context) (result []*PropertyUnitType, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedUnitTypes(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.UnitTypesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryUnitTypes().All(ctx)
	}
	return result, err
}

func (_m *Property) OpenHouses(ctx context.Context) (result []*OpenHouse, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedOpenHouses(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.OpenHousesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryOpenHouses().All(ctx)
	}
	return result, err
}

func (_m *PropertyRoom) Property(ctx context.Context) (*Property, error) {
	result, err := _m.Edges.PropertyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProperty().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *PropertyUnitType) Property(ctx context.Context) (*Property, error) {
	result, err := _m.Edges.PropertyOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryProperty().Only(ctx)
	}
	return result, MaskNotFound(err)
}
