// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/mediaversion"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/predicate"
	"github.com/google/uuid"
)

// MediaVersionUpdate is the builder for updating MediaVersion entities.
type MediaVersionUpdate struct {
	config
	hooks    []Hook
	mutation *MediaVersionMutation
}

// Where appends a list predicates to the MediaVersionUpdate builder.
func (_u *MediaVersionUpdate) Where(ps ...predicate.MediaVersion) *MediaVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *MediaVersionUpdate) SetValidFrom(v time.Time) *MediaVersionUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableValidFrom(v *time.Time) *MediaVersionUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *MediaVersionUpdate) SetValidTo(v time.Time) *MediaVersionUpdate {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableValidTo(v *time.Time) *MediaVersionUpdate {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *MediaVersionUpdate) ClearValidTo() *MediaVersionUpdate {
	_u.mutation.ClearValidTo()
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *MediaVersionUpdate) SetChangeType(v mediaversion.ChangeType) *MediaVersionUpdate {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableChangeType(v *mediaversion.ChangeType) *MediaVersionUpdate {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetChangedFields sets the "changed_fields" field.
func (_u *MediaVersionUpdate) SetChangedFields(v map[string]interface{}) *MediaVersionUpdate {
	_u.mutation.SetChangedFields(v)
	return _u
}

// ClearChangedFields clears the value of the "changed_fields" field.
func (_u *MediaVersionUpdate) ClearChangedFields() *MediaVersionUpdate {
	_u.mutation.ClearChangedFields()
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *MediaVersionUpdate) SetProcessorVersion(v string) *MediaVersionUpdate {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableProcessorVersion(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// SetSyncEventID sets the "sync_event_id" field.
func (_u *MediaVersionUpdate) SetSyncEventID(v uuid.UUID) *MediaVersionUpdate {
	_u.mutation.SetSyncEventID(v)
	return _u
}

// SetNillableSyncEventID sets the "sync_event_id" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableSyncEventID(v *uuid.UUID) *MediaVersionUpdate {
	if v != nil {
		_u.SetSyncEventID(*v)
	}
	return _u
}

// SetRawOutputID sets the "raw_output_id" field.
func (_u *MediaVersionUpdate) SetRawOutputID(v uuid.UUID) *MediaVersionUpdate {
	_u.mutation.SetRawOutputID(v)
	return _u
}

// SetNillableRawOutputID sets the "raw_output_id" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableRawOutputID(v *uuid.UUID) *MediaVersionUpdate {
	if v != nil {
		_u.SetRawOutputID(*v)
	}
	return _u
}

// ClearRawOutputID clears the value of the "raw_output_id" field.
func (_u *MediaVersionUpdate) ClearRawOutputID() *MediaVersionUpdate {
	_u.mutation.ClearRawOutputID()
	return _u
}

// SetSourceModifiedAt sets the "source_modified_at" field.
func (_u *MediaVersionUpdate) SetSourceModifiedAt(v time.Time) *MediaVersionUpdate {
	_u.mutation.SetSourceModifiedAt(v)
	return _u
}

// SetNillableSourceModifiedAt sets the "source_modified_at" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableSourceModifiedAt(v *time.Time) *MediaVersionUpdate {
	if v != nil {
		_u.SetSourceModifiedAt(*v)
	}
	return _u
}

// SetOriginatingSystemName sets the "originating_system_name" field.
func (_u *MediaVersionUpdate) SetOriginatingSystemName(v string) *MediaVersionUpdate {
	_u.mutation.SetOriginatingSystemName(v)
	return _u
}

// SetNillableOriginatingSystemName sets the "originating_system_name" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableOriginatingSystemName(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetOriginatingSystemName(*v)
	}
	return _u
}

// ClearOriginatingSystemName clears the value of the "originating_system_name" field.
func (_u *MediaVersionUpdate) ClearOriginatingSystemName() *MediaVersionUpdate {
	_u.mutation.ClearOriginatingSystemName()
	return _u
}

// SetMlgCanView sets the "mlg_can_view" field.
func (_u *MediaVersionUpdate) SetMlgCanView(v bool) *MediaVersionUpdate {
	_u.mutation.SetMlgCanView(v)
	return _u
}

// SetNillableMlgCanView sets the "mlg_can_view" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableMlgCanView(v *bool) *MediaVersionUpdate {
	if v != nil {
		_u.SetMlgCanView(*v)
	}
	return _u
}

// SetMlgCanUse sets the "mlg_can_use" field.
func (_u *MediaVersionUpdate) SetMlgCanUse(v []string) *MediaVersionUpdate {
	_u.mutation.SetMlgCanUse(v)
	return _u
}

// AppendMlgCanUse appends value to the "mlg_can_use" field.
func (_u *MediaVersionUpdate) AppendMlgCanUse(v []string) *MediaVersionUpdate {
	_u.mutation.AppendMlgCanUse(v)
	return _u
}

// ClearMlgCanUse clears the value of the "mlg_can_use" field.
func (_u *MediaVersionUpdate) ClearMlgCanUse() *MediaVersionUpdate {
	_u.mutation.ClearMlgCanUse()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *MediaVersionUpdate) SetResourceType(v mediaversion.ResourceType) *MediaVersionUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableResourceType(v *mediaversion.ResourceType) *MediaVersionUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceRecordKey sets the "resource_record_key" field.
func (_u *MediaVersionUpdate) SetResourceRecordKey(v string) *MediaVersionUpdate {
	_u.mutation.SetResourceRecordKey(v)
	return _u
}

// SetNillableResourceRecordKey sets the "resource_record_key" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableResourceRecordKey(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetResourceRecordKey(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaVersionUpdate) SetMediaType(v string) *MediaVersionUpdate {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableMediaType(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// ClearMediaType clears the value of the "media_type" field.
func (_u *MediaVersionUpdate) ClearMediaType() *MediaVersionUpdate {
	_u.mutation.ClearMediaType()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *MediaVersionUpdate) SetMediaURL(v string) *MediaVersionUpdate {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableMediaURL(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *MediaVersionUpdate) ClearMediaURL() *MediaVersionUpdate {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetImageHeight sets the "image_height" field.
func (_u *MediaVersionUpdate) SetImageHeight(v int64) *MediaVersionUpdate {
	_u.mutation.ResetImageHeight()
	_u.mutation.SetImageHeight(v)
	return _u
}

// SetNillableImageHeight sets the "image_height" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableImageHeight(v *int64) *MediaVersionUpdate {
	if v != nil {
		_u.SetImageHeight(*v)
	}
	return _u
}

// AddImageHeight adds value to the "image_height" field.
func (_u *MediaVersionUpdate) AddImageHeight(v int64) *MediaVersionUpdate {
	_u.mutation.AddImageHeight(v)
	return _u
}

// ClearImageHeight clears the value of the "image_height" field.
func (_u *MediaVersionUpdate) ClearImageHeight() *MediaVersionUpdate {
	_u.mutation.ClearImageHeight()
	return _u
}

// SetImageWidth sets the "image_width" field.
func (_u *MediaVersionUpdate) SetImageWidth(v int64) *MediaVersionUpdate {
	_u.mutation.ResetImageWidth()
	_u.mutation.SetImageWidth(v)
	return _u
}

// SetNillableImageWidth sets the "image_width" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableImageWidth(v *int64) *MediaVersionUpdate {
	if v != nil {
		_u.SetImageWidth(*v)
	}
	return _u
}

// AddImageWidth adds value to the "image_width" field.
func (_u *MediaVersionUpdate) AddImageWidth(v int64) *MediaVersionUpdate {
	_u.mutation.AddImageWidth(v)
	return _u
}

// ClearImageWidth clears the value of the "image_width" field.
func (_u *MediaVersionUpdate) ClearImageWidth() *MediaVersionUpdate {
	_u.mutation.ClearImageWidth()
	return _u
}

// SetImageSizeDescription sets the "image_size_description" field.
func (_u *MediaVersionUpdate) SetImageSizeDescription(v string) *MediaVersionUpdate {
	_u.mutation.SetImageSizeDescription(v)
	return _u
}

// SetNillableImageSizeDescription sets the "image_size_description" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableImageSizeDescription(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetImageSizeDescription(*v)
	}
	return _u
}

// ClearImageSizeDescription clears the value of the "image_size_description" field.
func (_u *MediaVersionUpdate) ClearImageSizeDescription() *MediaVersionUpdate {
	_u.mutation.ClearImageSizeDescription()
	return _u
}

// SetLongDescription sets the "long_description" field.
func (_u *MediaVersionUpdate) SetLongDescription(v string) *MediaVersionUpdate {
	_u.mutation.SetLongDescription(v)
	return _u
}

// SetNillableLongDescription sets the "long_description" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableLongDescription(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetLongDescription(*v)
	}
	return _u
}

// ClearLongDescription clears the value of the "long_description" field.
func (_u *MediaVersionUpdate) ClearLongDescription() *MediaVersionUpdate {
	_u.mutation.ClearLongDescription()
	return _u
}

// SetOrder sets the "order" field.
func (_u *MediaVersionUpdate) SetOrder(v int16) *MediaVersionUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableOrder(v *int16) *MediaVersionUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *MediaVersionUpdate) AddOrder(v int16) *MediaVersionUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *MediaVersionUpdate) ClearOrder() *MediaVersionUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// SetPreferredPhotoYn sets the "preferred_photo_yn" field.
func (_u *MediaVersionUpdate) SetPreferredPhotoYn(v bool) *MediaVersionUpdate {
	_u.mutation.SetPreferredPhotoYn(v)
	return _u
}

// SetNillablePreferredPhotoYn sets the "preferred_photo_yn" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillablePreferredPhotoYn(v *bool) *MediaVersionUpdate {
	if v != nil {
		_u.SetPreferredPhotoYn(*v)
	}
	return _u
}

// ClearPreferredPhotoYn clears the value of the "preferred_photo_yn" field.
func (_u *MediaVersionUpdate) ClearPreferredPhotoYn() *MediaVersionUpdate {
	_u.mutation.ClearPreferredPhotoYn()
	return _u
}

// SetMediaModificationTimestamp sets the "media_modification_timestamp" field.
func (_u *MediaVersionUpdate) SetMediaModificationTimestamp(v time.Time) *MediaVersionUpdate {
	_u.mutation.SetMediaModificationTimestamp(v)
	return _u
}

// SetNillableMediaModificationTimestamp sets the "media_modification_timestamp" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableMediaModificationTimestamp(v *time.Time) *MediaVersionUpdate {
	if v != nil {
		_u.SetMediaModificationTimestamp(*v)
	}
	return _u
}

// ClearMediaModificationTimestamp clears the value of the "media_modification_timestamp" field.
func (_u *MediaVersionUpdate) ClearMediaModificationTimestamp() *MediaVersionUpdate {
	_u.mutation.ClearMediaModificationTimestamp()
	return _u
}

// SetExtendedFields sets the "extended_fields" field.
func (_u *MediaVersionUpdate) SetExtendedFields(v map[string]interface{}) *MediaVersionUpdate {
	_u.mutation.SetExtendedFields(v)
	return _u
}

// ClearExtendedFields clears the value of the "extended_fields" field.
func (_u *MediaVersionUpdate) ClearExtendedFields() *MediaVersionUpdate {
	_u.mutation.ClearExtendedFields()
	return _u
}

// SetMediaKey sets the "media_key" field.
func (_u *MediaVersionUpdate) SetMediaKey(v string) *MediaVersionUpdate {
	_u.mutation.SetMediaKey(v)
	return _u
}

// SetNillableMediaKey sets the "media_key" field if the given value is not nil.
func (_u *MediaVersionUpdate) SetNillableMediaKey(v *string) *MediaVersionUpdate {
	if v != nil {
		_u.SetMediaKey(*v)
	}
	return _u
}

// Mutation returns the MediaVersionMutation object of the builder.
func (_u *MediaVersionUpdate) Mutation() *MediaVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaVersionUpdate) check() error {
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := mediaversion.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "MediaVersion.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := mediaversion.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "MediaVersion.resource_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaversion.Table, mediaversion.Columns, sqlgraph.NewFieldSpec(mediaversion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(mediaversion.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(mediaversion.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(mediaversion.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(mediaversion.FieldChangeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ChangedFields(); ok {
		_spec.SetField(mediaversion.FieldChangedFields, field.TypeJSON, value)
	}
	if _u.mutation.ChangedFieldsCleared() {
		_spec.ClearField(mediaversion.FieldChangedFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(mediaversion.FieldProcessorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncEventID(); ok {
		_spec.SetField(mediaversion.FieldSyncEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RawOutputID(); ok {
		_spec.SetField(mediaversion.FieldRawOutputID, field.TypeUUID, value)
	}
	if _u.mutation.RawOutputIDCleared() {
		_spec.ClearField(mediaversion.FieldRawOutputID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceModifiedAt(); ok {
		_spec.SetField(mediaversion.FieldSourceModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginatingSystemName(); ok {
		_spec.SetField(mediaversion.FieldOriginatingSystemName, field.TypeString, value)
	}
	if _u.mutation.OriginatingSystemNameCleared() {
		_spec.ClearField(mediaversion.FieldOriginatingSystemName, field.TypeString)
	}
	if value, ok := _u.mutation.MlgCanView(); ok {
		_spec.SetField(mediaversion.FieldMlgCanView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MlgCanUse(); ok {
		_spec.SetField(mediaversion.FieldMlgCanUse, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMlgCanUse(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaversion.FieldMlgCanUse, value)
		})
	}
	if _u.mutation.MlgCanUseCleared() {
		_spec.ClearField(mediaversion.FieldMlgCanUse, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(mediaversion.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceRecordKey(); ok {
		_spec.SetField(mediaversion.FieldResourceRecordKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediaversion.FieldMediaType, field.TypeString, value)
	}
	if _u.mutation.MediaTypeCleared() {
		_spec.ClearField(mediaversion.FieldMediaType, field.TypeString)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(mediaversion.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(mediaversion.FieldMediaURL, field.TypeString)
	}
	if value, ok := _u.mutation.ImageHeight(); ok {
		_spec.SetField(mediaversion.FieldImageHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageHeight(); ok {
		_spec.AddField(mediaversion.FieldImageHeight, field.TypeInt64, value)
	}
	if _u.mutation.ImageHeightCleared() {
		_spec.ClearField(mediaversion.FieldImageHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageWidth(); ok {
		_spec.SetField(mediaversion.FieldImageWidth, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageWidth(); ok {
		_spec.AddField(mediaversion.FieldImageWidth, field.TypeInt64, value)
	}
	if _u.mutation.ImageWidthCleared() {
		_spec.ClearField(mediaversion.FieldImageWidth, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageSizeDescription(); ok {
		_spec.SetField(mediaversion.FieldImageSizeDescription, field.TypeString, value)
	}
	if _u.mutation.ImageSizeDescriptionCleared() {
		_spec.ClearField(mediaversion.FieldImageSizeDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LongDescription(); ok {
		_spec.SetField(mediaversion.FieldLongDescription, field.TypeString, value)
	}
	if _u.mutation.LongDescriptionCleared() {
		_spec.ClearField(mediaversion.FieldLongDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(mediaversion.FieldOrder, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(mediaversion.FieldOrder, field.TypeInt16, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(mediaversion.FieldOrder, field.TypeInt16)
	}
	if value, ok := _u.mutation.PreferredPhotoYn(); ok {
		_spec.SetField(mediaversion.FieldPreferredPhotoYn, field.TypeBool, value)
	}
	if _u.mutation.PreferredPhotoYnCleared() {
		_spec.ClearField(mediaversion.FieldPreferredPhotoYn, field.TypeBool)
	}
	if value, ok := _u.mutation.MediaModificationTimestamp(); ok {
		_spec.SetField(mediaversion.FieldMediaModificationTimestamp, field.TypeTime, value)
	}
	if _u.mutation.MediaModificationTimestampCleared() {
		_spec.ClearField(mediaversion.FieldMediaModificationTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.ExtendedFields(); ok {
		_spec.SetField(mediaversion.FieldExtendedFields, field.TypeJSON, value)
	}
	if _u.mutation.ExtendedFieldsCleared() {
		_spec.ClearField(mediaversion.FieldExtendedFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.MediaKey(); ok {
		_spec.SetField(mediaversion.FieldMediaKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaVersionUpdateOne is the builder for updating a single MediaVersion entity.
type MediaVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaVersionMutation
}

// SetValidFrom sets the "valid_from" field.
func (_u *MediaVersionUpdateOne) SetValidFrom(v time.Time) *MediaVersionUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableValidFrom(v *time.Time) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *MediaVersionUpdateOne) SetValidTo(v time.Time) *MediaVersionUpdateOne {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableValidTo(v *time.Time) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *MediaVersionUpdateOne) ClearValidTo() *MediaVersionUpdateOne {
	_u.mutation.ClearValidTo()
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *MediaVersionUpdateOne) SetChangeType(v mediaversion.ChangeType) *MediaVersionUpdateOne {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableChangeType(v *mediaversion.ChangeType) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetChangedFields sets the "changed_fields" field.
func (_u *MediaVersionUpdateOne) SetChangedFields(v map[string]interface{}) *MediaVersionUpdateOne {
	_u.mutation.SetChangedFields(v)
	return _u
}

// ClearChangedFields clears the value of the "changed_fields" field.
func (_u *MediaVersionUpdateOne) ClearChangedFields() *MediaVersionUpdateOne {
	_u.mutation.ClearChangedFields()
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *MediaVersionUpdateOne) SetProcessorVersion(v string) *MediaVersionUpdateOne {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableProcessorVersion(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// SetSyncEventID sets the "sync_event_id" field.
func (_u *MediaVersionUpdateOne) SetSyncEventID(v uuid.UUID) *MediaVersionUpdateOne {
	_u.mutation.SetSyncEventID(v)
	return _u
}

// SetNillableSyncEventID sets the "sync_event_id" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableSyncEventID(v *uuid.UUID) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetSyncEventID(*v)
	}
	return _u
}

// SetRawOutputID sets the "raw_output_id" field.
func (_u *MediaVersionUpdateOne) SetRawOutputID(v uuid.UUID) *MediaVersionUpdateOne {
	_u.mutation.SetRawOutputID(v)
	return _u
}

// SetNillableRawOutputID sets the "raw_output_id" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableRawOutputID(v *uuid.UUID) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetRawOutputID(*v)
	}
	return _u
}

// ClearRawOutputID clears the value of the "raw_output_id" field.
func (_u *MediaVersionUpdateOne) ClearRawOutputID() *MediaVersionUpdateOne {
	_u.mutation.ClearRawOutputID()
	return _u
}

// SetSourceModifiedAt sets the "source_modified_at" field.
func (_u *MediaVersionUpdateOne) SetSourceModifiedAt(v time.Time) *MediaVersionUpdateOne {
	_u.mutation.SetSourceModifiedAt(v)
	return _u
}

// SetNillableSourceModifiedAt sets the "source_modified_at" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableSourceModifiedAt(v *time.Time) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetSourceModifiedAt(*v)
	}
	return _u
}

// SetOriginatingSystemName sets the "originating_system_name" field.
func (_u *MediaVersionUpdateOne) SetOriginatingSystemName(v string) *MediaVersionUpdateOne {
	_u.mutation.SetOriginatingSystemName(v)
	return _u
}

// SetNillableOriginatingSystemName sets the "originating_system_name" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableOriginatingSystemName(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetOriginatingSystemName(*v)
	}
	return _u
}

// ClearOriginatingSystemName clears the value of the "originating_system_name" field.
func (_u *MediaVersionUpdateOne) ClearOriginatingSystemName() *MediaVersionUpdateOne {
	_u.mutation.ClearOriginatingSystemName()
	return _u
}

// SetMlgCanView sets the "mlg_can_view" field.
func (_u *MediaVersionUpdateOne) SetMlgCanView(v bool) *MediaVersionUpdateOne {
	_u.mutation.SetMlgCanView(v)
	return _u
}

// SetNillableMlgCanView sets the "mlg_can_view" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableMlgCanView(v *bool) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetMlgCanView(*v)
	}
	return _u
}

// SetMlgCanUse sets the "mlg_can_use" field.
func (_u *MediaVersionUpdateOne) SetMlgCanUse(v []string) *MediaVersionUpdateOne {
	_u.mutation.SetMlgCanUse(v)
	return _u
}

// AppendMlgCanUse appends value to the "mlg_can_use" field.
func (_u *MediaVersionUpdateOne) AppendMlgCanUse(v []string) *MediaVersionUpdateOne {
	_u.mutation.AppendMlgCanUse(v)
	return _u
}

// ClearMlgCanUse clears the value of the "mlg_can_use" field.
func (_u *MediaVersionUpdateOne) ClearMlgCanUse() *MediaVersionUpdateOne {
	_u.mutation.ClearMlgCanUse()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *MediaVersionUpdateOne) SetResourceType(v mediaversion.ResourceType) *MediaVersionUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableResourceType(v *mediaversion.ResourceType) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceRecordKey sets the "resource_record_key" field.
func (_u *MediaVersionUpdateOne) SetResourceRecordKey(v string) *MediaVersionUpdateOne {
	_u.mutation.SetResourceRecordKey(v)
	return _u
}

// SetNillableResourceRecordKey sets the "resource_record_key" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableResourceRecordKey(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetResourceRecordKey(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaVersionUpdateOne) SetMediaType(v string) *MediaVersionUpdateOne {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableMediaType(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// ClearMediaType clears the value of the "media_type" field.
func (_u *MediaVersionUpdateOne) ClearMediaType() *MediaVersionUpdateOne {
	_u.mutation.ClearMediaType()
	return _u
}

// SetMediaURL sets the "media_url" field.
func (_u *MediaVersionUpdateOne) SetMediaURL(v string) *MediaVersionUpdateOne {
	_u.mutation.SetMediaURL(v)
	return _u
}

// SetNillableMediaURL sets the "media_url" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableMediaURL(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetMediaURL(*v)
	}
	return _u
}

// ClearMediaURL clears the value of the "media_url" field.
func (_u *MediaVersionUpdateOne) ClearMediaURL() *MediaVersionUpdateOne {
	_u.mutation.ClearMediaURL()
	return _u
}

// SetImageHeight sets the "image_height" field.
func (_u *MediaVersionUpdateOne) SetImageHeight(v int64) *MediaVersionUpdateOne {
	_u.mutation.ResetImageHeight()
	_u.mutation.SetImageHeight(v)
	return _u
}

// SetNillableImageHeight sets the "image_height" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableImageHeight(v *int64) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetImageHeight(*v)
	}
	return _u
}

// AddImageHeight adds value to the "image_height" field.
func (_u *MediaVersionUpdateOne) AddImageHeight(v int64) *MediaVersionUpdateOne {
	_u.mutation.AddImageHeight(v)
	return _u
}

// ClearImageHeight clears the value of the "image_height" field.
func (_u *MediaVersionUpdateOne) ClearImageHeight() *MediaVersionUpdateOne {
	_u.mutation.ClearImageHeight()
	return _u
}

// SetImageWidth sets the "image_width" field.
func (_u *MediaVersionUpdateOne) SetImageWidth(v int64) *MediaVersionUpdateOne {
	_u.mutation.ResetImageWidth()
	_u.mutation.SetImageWidth(v)
	return _u
}

// SetNillableImageWidth sets the "image_width" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableImageWidth(v *int64) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetImageWidth(*v)
	}
	return _u
}

// AddImageWidth adds value to the "image_width" field.
func (_u *MediaVersionUpdateOne) AddImageWidth(v int64) *MediaVersionUpdateOne {
	_u.mutation.AddImageWidth(v)
	return _u
}

// ClearImageWidth clears the value of the "image_width" field.
func (_u *MediaVersionUpdateOne) ClearImageWidth() *MediaVersionUpdateOne {
	_u.mutation.ClearImageWidth()
	return _u
}

// SetImageSizeDescription sets the "image_size_description" field.
func (_u *MediaVersionUpdateOne) SetImageSizeDescription(v string) *MediaVersionUpdateOne {
	_u.mutation.SetImageSizeDescription(v)
	return _u
}

// SetNillableImageSizeDescription sets the "image_size_description" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableImageSizeDescription(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetImageSizeDescription(*v)
	}
	return _u
}

// ClearImageSizeDescription clears the value of the "image_size_description" field.
func (_u *MediaVersionUpdateOne) ClearImageSizeDescription() *MediaVersionUpdateOne {
	_u.mutation.ClearImageSizeDescription()
	return _u
}

// SetLongDescription sets the "long_description" field.
func (_u *MediaVersionUpdateOne) SetLongDescription(v string) *MediaVersionUpdateOne {
	_u.mutation.SetLongDescription(v)
	return _u
}

// SetNillableLongDescription sets the "long_description" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableLongDescription(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetLongDescription(*v)
	}
	return _u
}

// ClearLongDescription clears the value of the "long_description" field.
func (_u *MediaVersionUpdateOne) ClearLongDescription() *MediaVersionUpdateOne {
	_u.mutation.ClearLongDescription()
	return _u
}

// SetOrder sets the "order" field.
func (_u *MediaVersionUpdateOne) SetOrder(v int16) *MediaVersionUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableOrder(v *int16) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *MediaVersionUpdateOne) AddOrder(v int16) *MediaVersionUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// ClearOrder clears the value of the "order" field.
func (_u *MediaVersionUpdateOne) ClearOrder() *MediaVersionUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// SetPreferredPhotoYn sets the "preferred_photo_yn" field.
func (_u *MediaVersionUpdateOne) SetPreferredPhotoYn(v bool) *MediaVersionUpdateOne {
	_u.mutation.SetPreferredPhotoYn(v)
	return _u
}

// SetNillablePreferredPhotoYn sets the "preferred_photo_yn" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillablePreferredPhotoYn(v *bool) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetPreferredPhotoYn(*v)
	}
	return _u
}

// ClearPreferredPhotoYn clears the value of the "preferred_photo_yn" field.
func (_u *MediaVersionUpdateOne) ClearPreferredPhotoYn() *MediaVersionUpdateOne {
	_u.mutation.ClearPreferredPhotoYn()
	return _u
}

// SetMediaModificationTimestamp sets the "media_modification_timestamp" field.
func (_u *MediaVersionUpdateOne) SetMediaModificationTimestamp(v time.Time) *MediaVersionUpdateOne {
	_u.mutation.SetMediaModificationTimestamp(v)
	return _u
}

// SetNillableMediaModificationTimestamp sets the "media_modification_timestamp" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableMediaModificationTimestamp(v *time.Time) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetMediaModificationTimestamp(*v)
	}
	return _u
}

// ClearMediaModificationTimestamp clears the value of the "media_modification_timestamp" field.
func (_u *MediaVersionUpdateOne) ClearMediaModificationTimestamp() *MediaVersionUpdateOne {
	_u.mutation.ClearMediaModificationTimestamp()
	return _u
}

// SetExtendedFields sets the "extended_fields" field.
func (_u *MediaVersionUpdateOne) SetExtendedFields(v map[string]interface{}) *MediaVersionUpdateOne {
	_u.mutation.SetExtendedFields(v)
	return _u
}

// ClearExtendedFields clears the value of the "extended_fields" field.
func (_u *MediaVersionUpdateOne) ClearExtendedFields() *MediaVersionUpdateOne {
	_u.mutation.ClearExtendedFields()
	return _u
}

// SetMediaKey sets the "media_key" field.
func (_u *MediaVersionUpdateOne) SetMediaKey(v string) *MediaVersionUpdateOne {
	_u.mutation.SetMediaKey(v)
	return _u
}

// SetNillableMediaKey sets the "media_key" field if the given value is not nil.
func (_u *MediaVersionUpdateOne) SetNillableMediaKey(v *string) *MediaVersionUpdateOne {
	if v != nil {
		_u.SetMediaKey(*v)
	}
	return _u
}

// Mutation returns the MediaVersionMutation object of the builder.
func (_u *MediaVersionUpdateOne) Mutation() *MediaVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaVersionUpdate builder.
func (_u *MediaVersionUpdateOne) Where(ps ...predicate.MediaVersion) *MediaVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaVersionUpdateOne) Select(field string, fields ...string) *MediaVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaVersion entity.
func (_u *MediaVersionUpdateOne) Save(ctx context.Context) (*MediaVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaVersionUpdateOne) SaveX(ctx context.Context) *MediaVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := mediaversion.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "MediaVersion.change_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := mediaversion.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "MediaVersion.resource_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaVersionUpdateOne) sqlSave(ctx context.Context) (_node *MediaVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaversion.Table, mediaversion.Columns, sqlgraph.NewFieldSpec(mediaversion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaversion.FieldID)
		for _, f := range fields {
			if !mediaversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(mediaversion.FieldValidFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(mediaversion.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(mediaversion.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(mediaversion.FieldChangeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ChangedFields(); ok {
		_spec.SetField(mediaversion.FieldChangedFields, field.TypeJSON, value)
	}
	if _u.mutation.ChangedFieldsCleared() {
		_spec.ClearField(mediaversion.FieldChangedFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(mediaversion.FieldProcessorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncEventID(); ok {
		_spec.SetField(mediaversion.FieldSyncEventID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RawOutputID(); ok {
		_spec.SetField(mediaversion.FieldRawOutputID, field.TypeUUID, value)
	}
	if _u.mutation.RawOutputIDCleared() {
		_spec.ClearField(mediaversion.FieldRawOutputID, field.TypeUUID)
	}
	if value, ok := _u.mutation.SourceModifiedAt(); ok {
		_spec.SetField(mediaversion.FieldSourceModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginatingSystemName(); ok {
		_spec.SetField(mediaversion.FieldOriginatingSystemName, field.TypeString, value)
	}
	if _u.mutation.OriginatingSystemNameCleared() {
		_spec.ClearField(mediaversion.FieldOriginatingSystemName, field.TypeString)
	}
	if value, ok := _u.mutation.MlgCanView(); ok {
		_spec.SetField(mediaversion.FieldMlgCanView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MlgCanUse(); ok {
		_spec.SetField(mediaversion.FieldMlgCanUse, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMlgCanUse(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediaversion.FieldMlgCanUse, value)
		})
	}
	if _u.mutation.MlgCanUseCleared() {
		_spec.ClearField(mediaversion.FieldMlgCanUse, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(mediaversion.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceRecordKey(); ok {
		_spec.SetField(mediaversion.FieldResourceRecordKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediaversion.FieldMediaType, field.TypeString, value)
	}
	if _u.mutation.MediaTypeCleared() {
		_spec.ClearField(mediaversion.FieldMediaType, field.TypeString)
	}
	if value, ok := _u.mutation.MediaURL(); ok {
		_spec.SetField(mediaversion.FieldMediaURL, field.TypeString, value)
	}
	if _u.mutation.MediaURLCleared() {
		_spec.ClearField(mediaversion.FieldMediaURL, field.TypeString)
	}
	if value, ok := _u.mutation.ImageHeight(); ok {
		_spec.SetField(mediaversion.FieldImageHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageHeight(); ok {
		_spec.AddField(mediaversion.FieldImageHeight, field.TypeInt64, value)
	}
	if _u.mutation.ImageHeightCleared() {
		_spec.ClearField(mediaversion.FieldImageHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageWidth(); ok {
		_spec.SetField(mediaversion.FieldImageWidth, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageWidth(); ok {
		_spec.AddField(mediaversion.FieldImageWidth, field.TypeInt64, value)
	}
	if _u.mutation.ImageWidthCleared() {
		_spec.ClearField(mediaversion.FieldImageWidth, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageSizeDescription(); ok {
		_spec.SetField(mediaversion.FieldImageSizeDescription, field.TypeString, value)
	}
	if _u.mutation.ImageSizeDescriptionCleared() {
		_spec.ClearField(mediaversion.FieldImageSizeDescription, field.TypeString)
	}
	if value, ok := _u.mutation.LongDescription(); ok {
		_spec.SetField(mediaversion.FieldLongDescription, field.TypeString, value)
	}
	if _u.mutation.LongDescriptionCleared() {
		_spec.ClearField(mediaversion.FieldLongDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(mediaversion.FieldOrder, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(mediaversion.FieldOrder, field.TypeInt16, value)
	}
	if _u.mutation.OrderCleared() {
		_spec.ClearField(mediaversion.FieldOrder, field.TypeInt16)
	}
	if value, ok := _u.mutation.PreferredPhotoYn(); ok {
		_spec.SetField(mediaversion.FieldPreferredPhotoYn, field.TypeBool, value)
	}
	if _u.mutation.PreferredPhotoYnCleared() {
		_spec.ClearField(mediaversion.FieldPreferredPhotoYn, field.TypeBool)
	}
	if value, ok := _u.mutation.MediaModificationTimestamp(); ok {
		_spec.SetField(mediaversion.FieldMediaModificationTimestamp, field.TypeTime, value)
	}
	if _u.mutation.MediaModificationTimestampCleared() {
		_spec.ClearField(mediaversion.FieldMediaModificationTimestamp, field.TypeTime)
	}
	if value, ok := _u.mutation.ExtendedFields(); ok {
		_spec.SetField(mediaversion.FieldExtendedFields, field.TypeJSON, value)
	}
	if _u.mutation.ExtendedFieldsCleared() {
		_spec.ClearField(mediaversion.FieldExtendedFields, field.TypeJSON)
	}
	if value, ok := _u.mutation.MediaKey(); ok {
		_spec.SetField(mediaversion.FieldMediaKey, field.TypeString, value)
	}
	_node = &MediaVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
