// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/office"
)

// Office is the model entity for the Office schema.
type Office struct {
	config `json:"-"`
	// ID of the ent.
	// PK = OfficeKey (canonical identifier from MLS Grid)
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ModifiedAt holds the value of the "modified_at" field.
	ModifiedAt time.Time `json:"modified_at,omitempty"`
	// Upstream ModificationTimestamp — canonical ordering
	SourceModifiedAt time.Time `json:"source_modified_at,omitempty"`
	// OriginatingSystemName holds the value of the "originating_system_name" field.
	OriginatingSystemName *string `json:"originating_system_name,omitempty"`
	// MLS Grid delete flag — false means record is removed upstream
	MlgCanView bool `json:"mlg_can_view,omitempty"`
	// Allowed use-case groups
	MlgCanUse []string `json:"mlg_can_use,omitempty"`
	// MLS-visible identifier; unique alt-key
	OfficeMlsID *string `json:"office_mls_id,omitempty"`
	// OfficeName holds the value of the "office_name" field.
	OfficeName *string `json:"office_name,omitempty"`
	// OfficeStatus holds the value of the "office_status" field.
	OfficeStatus *string `json:"office_status,omitempty"`
	// OfficeType holds the value of the "office_type" field.
	OfficeType *string `json:"office_type,omitempty"`
	// OfficePhone holds the value of the "office_phone" field.
	OfficePhone *string `json:"office_phone,omitempty"`
	// OfficePhoneExt holds the value of the "office_phone_ext" field.
	OfficePhoneExt *string `json:"office_phone_ext,omitempty"`
	// OfficeFax holds the value of the "office_fax" field.
	OfficeFax *string `json:"office_fax,omitempty"`
	// OfficeAddress1 holds the value of the "office_address1" field.
	OfficeAddress1 *string `json:"office_address1,omitempty"`
	// OfficeAddress2 holds the value of the "office_address2" field.
	OfficeAddress2 *string `json:"office_address2,omitempty"`
	// OfficeCity holds the value of the "office_city" field.
	OfficeCity *string `json:"office_city,omitempty"`
	// OfficeStateOrProvince holds the value of the "office_state_or_province" field.
	OfficeStateOrProvince *string `json:"office_state_or_province,omitempty"`
	// OfficePostalCode holds the value of the "office_postal_code" field.
	OfficePostalCode *string `json:"office_postal_code,omitempty"`
	// OfficePostalCodePlus4 holds the value of the "office_postal_code_plus4" field.
	OfficePostalCodePlus4 *string `json:"office_postal_code_plus4,omitempty"`
	// OfficeCountyOrParish holds the value of the "office_county_or_parish" field.
	OfficeCountyOrParish *string `json:"office_county_or_parish,omitempty"`
	// OfficeCorporateLicense holds the value of the "office_corporate_license" field.
	OfficeCorporateLicense *string `json:"office_corporate_license,omitempty"`
	// OfficeNationalAssociationID holds the value of the "office_national_association_id" field.
	OfficeNationalAssociationID *string `json:"office_national_association_id,omitempty"`
	// MainOfficeKey holds the value of the "main_office_key" field.
	MainOfficeKey *string `json:"main_office_key,omitempty"`
	// MainOfficeMlsID holds the value of the "main_office_mls_id" field.
	MainOfficeMlsID *string `json:"main_office_mls_id,omitempty"`
	// OfficeBrokerKey holds the value of the "office_broker_key" field.
	OfficeBrokerKey *string `json:"office_broker_key,omitempty"`
	// OfficeBrokerMlsID holds the value of the "office_broker_mls_id" field.
	OfficeBrokerMlsID *string `json:"office_broker_mls_id,omitempty"`
	// OfficeManagerKey holds the value of the "office_manager_key" field.
	OfficeManagerKey *string `json:"office_manager_key,omitempty"`
	// IdxOfficeParticipationYn holds the value of the "idx_office_participation_yn" field.
	IdxOfficeParticipationYn *bool `json:"idx_office_participation_yn,omitempty"`
	// PhotosChangeTimestamp holds the value of the "photos_change_timestamp" field.
	PhotosChangeTimestamp *time.Time `json:"photos_change_timestamp,omitempty"`
	// ExtendedFields holds the value of the "extended_fields" field.
	ExtendedFields map[string]interface{} `json:"extended_fields,omitempty"`
	// CurrentVersionID holds the value of the "current_version_id" field.
	CurrentVersionID *uuid.UUID `json:"current_version_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OfficeQuery when eager-loading is set.
	Edges        OfficeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OfficeEdges holds the relations/edges for other nodes in the graph.
type OfficeEdges struct {
	// MainOffice holds the value of the main_office edge.
	MainOffice *Office `json:"main_office,omitempty"`
	// Branches holds the value of the branches edge.
	Branches []*Office `json:"branches,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedBranches map[string][]*Office
}

// MainOfficeOrErr returns the MainOffice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfficeEdges) MainOfficeOrErr() (*Office, error) {
	if e.MainOffice != nil {
		return e.MainOffice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: office.Label}
	}
	return nil, &NotLoadedError{edge: "main_office"}
}

// BranchesOrErr returns the Branches value or an error if the edge
// was not loaded in eager-loading.
func (e OfficeEdges) BranchesOrErr() ([]*Office, error) {
	if e.loadedTypes[1] {
		return e.Branches, nil
	}
	return nil, &NotLoadedError{edge: "branches"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Office) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case office.FieldCurrentVersionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case office.FieldMlgCanUse, office.FieldExtendedFields:
			values[i] = new([]byte)
		case office.FieldMlgCanView, office.FieldIdxOfficeParticipationYn:
			values[i] = new(sql.NullBool)
		case office.FieldID, office.FieldOriginatingSystemName, office.FieldOfficeMlsID, office.FieldOfficeName, office.FieldOfficeStatus, office.FieldOfficeType, office.FieldOfficePhone, office.FieldOfficePhoneExt, office.FieldOfficeFax, office.FieldOfficeAddress1, office.FieldOfficeAddress2, office.FieldOfficeCity, office.FieldOfficeStateOrProvince, office.FieldOfficePostalCode, office.FieldOfficePostalCodePlus4, office.FieldOfficeCountyOrParish, office.FieldOfficeCorporateLicense, office.FieldOfficeNationalAssociationID, office.FieldMainOfficeKey, office.FieldMainOfficeMlsID, office.FieldOfficeBrokerKey, office.FieldOfficeBrokerMlsID, office.FieldOfficeManagerKey:
			values[i] = new(sql.NullString)
		case office.FieldCreatedAt, office.FieldModifiedAt, office.FieldSourceModifiedAt, office.FieldPhotosChangeTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Office fields.
func (_m *Office) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case office.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case office.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case office.FieldModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified_at", values[i])
			} else if value.Valid {
				_m.ModifiedAt = value.Time
			}
		case office.FieldSourceModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_modified_at", values[i])
			} else if value.Valid {
				_m.SourceModifiedAt = value.Time
			}
		case office.FieldOriginatingSystemName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field originating_system_name", values[i])
			} else if value.Valid {
				_m.OriginatingSystemName = new(string)
				*_m.OriginatingSystemName = value.String
			}
		case office.FieldMlgCanView:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mlg_can_view", values[i])
			} else if value.Valid {
				_m.MlgCanView = value.Bool
			}
		case office.FieldMlgCanUse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mlg_can_use", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MlgCanUse); err != nil {
					return fmt.Errorf("unmarshal field mlg_can_use: %w", err)
				}
			}
		case office.FieldOfficeMlsID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_mls_id", values[i])
			} else if value.Valid {
				_m.OfficeMlsID = new(string)
				*_m.OfficeMlsID = value.String
			}
		case office.FieldOfficeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_name", values[i])
			} else if value.Valid {
				_m.OfficeName = new(string)
				*_m.OfficeName = value.String
			}
		case office.FieldOfficeStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_status", values[i])
			} else if value.Valid {
				_m.OfficeStatus = new(string)
				*_m.OfficeStatus = value.String
			}
		case office.FieldOfficeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_type", values[i])
			} else if value.Valid {
				_m.OfficeType = new(string)
				*_m.OfficeType = value.String
			}
		case office.FieldOfficePhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_phone", values[i])
			} else if value.Valid {
				_m.OfficePhone = new(string)
				*_m.OfficePhone = value.String
			}
		case office.FieldOfficePhoneExt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_phone_ext", values[i])
			} else if value.Valid {
				_m.OfficePhoneExt = new(string)
				*_m.OfficePhoneExt = value.String
			}
		case office.FieldOfficeFax:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_fax", values[i])
			} else if value.Valid {
				_m.OfficeFax = new(string)
				*_m.OfficeFax = value.String
			}
		case office.FieldOfficeAddress1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_address1", values[i])
			} else if value.Valid {
				_m.OfficeAddress1 = new(string)
				*_m.OfficeAddress1 = value.String
			}
		case office.FieldOfficeAddress2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_address2", values[i])
			} else if value.Valid {
				_m.OfficeAddress2 = new(string)
				*_m.OfficeAddress2 = value.String
			}
		case office.FieldOfficeCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_city", values[i])
			} else if value.Valid {
				_m.OfficeCity = new(string)
				*_m.OfficeCity = value.String
			}
		case office.FieldOfficeStateOrProvince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_state_or_province", values[i])
			} else if value.Valid {
				_m.OfficeStateOrProvince = new(string)
				*_m.OfficeStateOrProvince = value.String
			}
		case office.FieldOfficePostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_postal_code", values[i])
			} else if value.Valid {
				_m.OfficePostalCode = new(string)
				*_m.OfficePostalCode = value.String
			}
		case office.FieldOfficePostalCodePlus4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_postal_code_plus4", values[i])
			} else if value.Valid {
				_m.OfficePostalCodePlus4 = new(string)
				*_m.OfficePostalCodePlus4 = value.String
			}
		case office.FieldOfficeCountyOrParish:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_county_or_parish", values[i])
			} else if value.Valid {
				_m.OfficeCountyOrParish = new(string)
				*_m.OfficeCountyOrParish = value.String
			}
		case office.FieldOfficeCorporateLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_corporate_license", values[i])
			} else if value.Valid {
				_m.OfficeCorporateLicense = new(string)
				*_m.OfficeCorporateLicense = value.String
			}
		case office.FieldOfficeNationalAssociationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_national_association_id", values[i])
			} else if value.Valid {
				_m.OfficeNationalAssociationID = new(string)
				*_m.OfficeNationalAssociationID = value.String
			}
		case office.FieldMainOfficeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field main_office_key", values[i])
			} else if value.Valid {
				_m.MainOfficeKey = new(string)
				*_m.MainOfficeKey = value.String
			}
		case office.FieldMainOfficeMlsID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field main_office_mls_id", values[i])
			} else if value.Valid {
				_m.MainOfficeMlsID = new(string)
				*_m.MainOfficeMlsID = value.String
			}
		case office.FieldOfficeBrokerKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_broker_key", values[i])
			} else if value.Valid {
				_m.OfficeBrokerKey = new(string)
				*_m.OfficeBrokerKey = value.String
			}
		case office.FieldOfficeBrokerMlsID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_broker_mls_id", values[i])
			} else if value.Valid {
				_m.OfficeBrokerMlsID = new(string)
				*_m.OfficeBrokerMlsID = value.String
			}
		case office.FieldOfficeManagerKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field office_manager_key", values[i])
			} else if value.Valid {
				_m.OfficeManagerKey = new(string)
				*_m.OfficeManagerKey = value.String
			}
		case office.FieldIdxOfficeParticipationYn:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field idx_office_participation_yn", values[i])
			} else if value.Valid {
				_m.IdxOfficeParticipationYn = new(bool)
				*_m.IdxOfficeParticipationYn = value.Bool
			}
		case office.FieldPhotosChangeTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field photos_change_timestamp", values[i])
			} else if value.Valid {
				_m.PhotosChangeTimestamp = new(time.Time)
				*_m.PhotosChangeTimestamp = value.Time
			}
		case office.FieldExtendedFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extended_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtendedFields); err != nil {
					return fmt.Errorf("unmarshal field extended_fields: %w", err)
				}
			}
		case office.FieldCurrentVersionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field current_version_id", values[i])
			} else if value.Valid {
				_m.CurrentVersionID = new(uuid.UUID)
				*_m.CurrentVersionID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Office.
// This includes values selected through modifiers, order, etc.
func (_m *Office) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMainOffice queries the "main_office" edge of the Office entity.
func (_m *Office) QueryMainOffice() *OfficeQuery {
	return NewOfficeClient(_m.config).QueryMainOffice(_m)
}

// QueryBranches queries the "branches" edge of the Office entity.
func (_m *Office) QueryBranches() *OfficeQuery {
	return NewOfficeClient(_m.config).QueryBranches(_m)
}

// Update returns a builder for updating this Office.
// Note that you need to call Office.Unwrap() before calling this method if this Office
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Office) Update() *OfficeUpdateOne {
	return NewOfficeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Office entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Office) Unwrap() *Office {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Office is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Office) String() string {
	var builder strings.Builder
	builder.WriteString("Office(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("modified_at=")
	builder.WriteString(_m.ModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_modified_at=")
	builder.WriteString(_m.SourceModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OriginatingSystemName; v != nil {
		builder.WriteString("originating_system_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mlg_can_view=")
	builder.WriteString(fmt.Sprintf("%v", _m.MlgCanView))
	builder.WriteString(", ")
	builder.WriteString("mlg_can_use=")
	builder.WriteString(fmt.Sprintf("%v", _m.MlgCanUse))
	builder.WriteString(", ")
	if v := _m.OfficeMlsID; v != nil {
		builder.WriteString("office_mls_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeName; v != nil {
		builder.WriteString("office_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeStatus; v != nil {
		builder.WriteString("office_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeType; v != nil {
		builder.WriteString("office_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficePhone; v != nil {
		builder.WriteString("office_phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficePhoneExt; v != nil {
		builder.WriteString("office_phone_ext=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeFax; v != nil {
		builder.WriteString("office_fax=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeAddress1; v != nil {
		builder.WriteString("office_address1=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeAddress2; v != nil {
		builder.WriteString("office_address2=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeCity; v != nil {
		builder.WriteString("office_city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeStateOrProvince; v != nil {
		builder.WriteString("office_state_or_province=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficePostalCode; v != nil {
		builder.WriteString("office_postal_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficePostalCodePlus4; v != nil {
		builder.WriteString("office_postal_code_plus4=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeCountyOrParish; v != nil {
		builder.WriteString("office_county_or_parish=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeCorporateLicense; v != nil {
		builder.WriteString("office_corporate_license=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeNationalAssociationID; v != nil {
		builder.WriteString("office_national_association_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MainOfficeKey; v != nil {
		builder.WriteString("main_office_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MainOfficeMlsID; v != nil {
		builder.WriteString("main_office_mls_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeBrokerKey; v != nil {
		builder.WriteString("office_broker_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeBrokerMlsID; v != nil {
		builder.WriteString("office_broker_mls_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OfficeManagerKey; v != nil {
		builder.WriteString("office_manager_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdxOfficeParticipationYn; v != nil {
		builder.WriteString("idx_office_participation_yn=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PhotosChangeTimestamp; v != nil {
		builder.WriteString("photos_change_timestamp=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("extended_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtendedFields))
	builder.WriteString(", ")
	if v := _m.CurrentVersionID; v != nil {
		builder.WriteString("current_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedBranches returns the Branches named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Office) NamedBranches(name string) ([]*Office, error) {
	if _m.Edges.namedBranches == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedBranches[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Office) appendNamedBranches(name string, edges ...*Office) {
	if _m.Edges.namedBranches == nil {
		_m.Edges.namedBranches = make(map[string][]*Office)
	}
	if len(edges) == 0 {
		_m.Edges.namedBranches[name] = []*Office{}
	} else {
		_m.Edges.namedBranches[name] = append(_m.Edges.namedBranches[name], edges...)
	}
}

// Offices is a parsable slice of Office.
type Offices []*Office
