// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/openhouseversion"
)

// OpenHouseVersion is the model entity for the OpenHouseVersion schema.
type OpenHouseVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// Nil means this is the current version
	ValidTo *time.Time `json:"valid_to,omitempty"`
	// ChangeType holds the value of the "change_type" field.
	ChangeType openhouseversion.ChangeType `json:"change_type,omitempty"`
	// Keys that differ from the prior version
	ChangedFields map[string]interface{} `json:"changed_fields,omitempty"`
	// ProcessorVersion holds the value of the "processor_version" field.
	ProcessorVersion string `json:"processor_version,omitempty"`
	// Upstream ModificationTimestamp — canonical ordering
	SourceModifiedAt time.Time `json:"source_modified_at,omitempty"`
	// OriginatingSystemName holds the value of the "originating_system_name" field.
	OriginatingSystemName *string `json:"originating_system_name,omitempty"`
	// MLS Grid delete flag — false means record is removed upstream
	MlgCanView bool `json:"mlg_can_view,omitempty"`
	// Allowed use-case groups
	MlgCanUse []string `json:"mlg_can_use,omitempty"`
	// FK to property.listing_key
	ListingKey string `json:"listing_key,omitempty"`
	// ListingID holds the value of the "listing_id" field.
	ListingID *string `json:"listing_id,omitempty"`
	// OpenHouseDate holds the value of the "open_house_date" field.
	OpenHouseDate *time.Time `json:"open_house_date,omitempty"`
	// OpenHouseStartTime holds the value of the "open_house_start_time" field.
	OpenHouseStartTime *time.Time `json:"open_house_start_time,omitempty"`
	// OpenHouseEndTime holds the value of the "open_house_end_time" field.
	OpenHouseEndTime *time.Time `json:"open_house_end_time,omitempty"`
	// OpenHouseStatus holds the value of the "open_house_status" field.
	OpenHouseStatus *string `json:"open_house_status,omitempty"`
	// OpenHouseType holds the value of the "open_house_type" field.
	OpenHouseType *string `json:"open_house_type,omitempty"`
	// ExtendedFields holds the value of the "extended_fields" field.
	ExtendedFields map[string]interface{} `json:"extended_fields,omitempty"`
	// OpenHouseKey holds the value of the "open_house_key" field.
	OpenHouseKey string `json:"open_house_key,omitempty"`
	// SyncEventID holds the value of the "sync_event_id" field.
	SyncEventID uuid.UUID `json:"sync_event_id,omitempty"`
	// RawOutputID holds the value of the "raw_output_id" field.
	RawOutputID  *uuid.UUID `json:"raw_output_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenHouseVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openhouseversion.FieldRawOutputID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case openhouseversion.FieldChangedFields, openhouseversion.FieldMlgCanUse, openhouseversion.FieldExtendedFields:
			values[i] = new([]byte)
		case openhouseversion.FieldMlgCanView:
			values[i] = new(sql.NullBool)
		case openhouseversion.FieldID, openhouseversion.FieldChangeType, openhouseversion.FieldProcessorVersion, openhouseversion.FieldOriginatingSystemName, openhouseversion.FieldListingKey, openhouseversion.FieldListingID, openhouseversion.FieldOpenHouseStatus, openhouseversion.FieldOpenHouseType, openhouseversion.FieldOpenHouseKey:
			values[i] = new(sql.NullString)
		case openhouseversion.FieldValidFrom, openhouseversion.FieldValidTo, openhouseversion.FieldSourceModifiedAt, openhouseversion.FieldOpenHouseDate, openhouseversion.FieldOpenHouseStartTime, openhouseversion.FieldOpenHouseEndTime:
			values[i] = new(sql.NullTime)
		case openhouseversion.FieldSyncEventID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenHouseVersion fields.
func (_m *OpenHouseVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openhouseversion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case openhouseversion.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case openhouseversion.FieldValidTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_to", values[i])
			} else if value.Valid {
				_m.ValidTo = new(time.Time)
				*_m.ValidTo = value.Time
			}
		case openhouseversion.FieldChangeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_type", values[i])
			} else if value.Valid {
				_m.ChangeType = openhouseversion.ChangeType(value.String)
			}
		case openhouseversion.FieldChangedFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field changed_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ChangedFields); err != nil {
					return fmt.Errorf("unmarshal field changed_fields: %w", err)
				}
			}
		case openhouseversion.FieldProcessorVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field processor_version", values[i])
			} else if value.Valid {
				_m.ProcessorVersion = value.String
			}
		case openhouseversion.FieldSourceModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_modified_at", values[i])
			} else if value.Valid {
				_m.SourceModifiedAt = value.Time
			}
		case openhouseversion.FieldOriginatingSystemName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field originating_system_name", values[i])
			} else if value.Valid {
				_m.OriginatingSystemName = new(string)
				*_m.OriginatingSystemName = value.String
			}
		case openhouseversion.FieldMlgCanView:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mlg_can_view", values[i])
			} else if value.Valid {
				_m.MlgCanView = value.Bool
			}
		case openhouseversion.FieldMlgCanUse:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mlg_can_use", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MlgCanUse); err != nil {
					return fmt.Errorf("unmarshal field mlg_can_use: %w", err)
				}
			}
		case openhouseversion.FieldListingKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field listing_key", values[i])
			} else if value.Valid {
				_m.ListingKey = value.String
			}
		case openhouseversion.FieldListingID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field listing_id", values[i])
			} else if value.Valid {
				_m.ListingID = new(string)
				*_m.ListingID = value.String
			}
		case openhouseversion.FieldOpenHouseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_date", values[i])
			} else if value.Valid {
				_m.OpenHouseDate = new(time.Time)
				*_m.OpenHouseDate = value.Time
			}
		case openhouseversion.FieldOpenHouseStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_start_time", values[i])
			} else if value.Valid {
				_m.OpenHouseStartTime = new(time.Time)
				*_m.OpenHouseStartTime = value.Time
			}
		case openhouseversion.FieldOpenHouseEndTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_end_time", values[i])
			} else if value.Valid {
				_m.OpenHouseEndTime = new(time.Time)
				*_m.OpenHouseEndTime = value.Time
			}
		case openhouseversion.FieldOpenHouseStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_status", values[i])
			} else if value.Valid {
				_m.OpenHouseStatus = new(string)
				*_m.OpenHouseStatus = value.String
			}
		case openhouseversion.FieldOpenHouseType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_type", values[i])
			} else if value.Valid {
				_m.OpenHouseType = new(string)
				*_m.OpenHouseType = value.String
			}
		case openhouseversion.FieldExtendedFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extended_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtendedFields); err != nil {
					return fmt.Errorf("unmarshal field extended_fields: %w", err)
				}
			}
		case openhouseversion.FieldOpenHouseKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field open_house_key", values[i])
			} else if value.Valid {
				_m.OpenHouseKey = value.String
			}
		case openhouseversion.FieldSyncEventID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field sync_event_id", values[i])
			} else if value != nil {
				_m.SyncEventID = *value
			}
		case openhouseversion.FieldRawOutputID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field raw_output_id", values[i])
			} else if value.Valid {
				_m.RawOutputID = new(uuid.UUID)
				*_m.RawOutputID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenHouseVersion.
// This includes values selected through modifiers, order, etc.
func (_m *OpenHouseVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenHouseVersion.
// Note that you need to call OpenHouseVersion.Unwrap() before calling this method if this OpenHouseVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenHouseVersion) Update() *OpenHouseVersionUpdateOne {
	return NewOpenHouseVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenHouseVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenHouseVersion) Unwrap() *OpenHouseVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenHouseVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenHouseVersion) String() string {
	var builder strings.Builder
	builder.WriteString("OpenHouseVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidTo; v != nil {
		builder.WriteString("valid_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("change_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChangeType))
	builder.WriteString(", ")
	builder.WriteString("changed_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChangedFields))
	builder.WriteString(", ")
	builder.WriteString("processor_version=")
	builder.WriteString(_m.ProcessorVersion)
	builder.WriteString(", ")
	builder.WriteString("source_modified_at=")
	builder.WriteString(_m.SourceModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.OriginatingSystemName; v != nil {
		builder.WriteString("originating_system_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mlg_can_view=")
	builder.WriteString(fmt.Sprintf("%v", _m.MlgCanView))
	builder.WriteString(", ")
	builder.WriteString("mlg_can_use=")
	builder.WriteString(fmt.Sprintf("%v", _m.MlgCanUse))
	builder.WriteString(", ")
	builder.WriteString("listing_key=")
	builder.WriteString(_m.ListingKey)
	builder.WriteString(", ")
	if v := _m.ListingID; v != nil {
		builder.WriteString("listing_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OpenHouseDate; v != nil {
		builder.WriteString("open_house_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OpenHouseStartTime; v != nil {
		builder.WriteString("open_house_start_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OpenHouseEndTime; v != nil {
		builder.WriteString("open_house_end_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.OpenHouseStatus; v != nil {
		builder.WriteString("open_house_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OpenHouseType; v != nil {
		builder.WriteString("open_house_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("extended_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtendedFields))
	builder.WriteString(", ")
	builder.WriteString("open_house_key=")
	builder.WriteString(_m.OpenHouseKey)
	builder.WriteString(", ")
	builder.WriteString("sync_event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncEventID))
	builder.WriteString(", ")
	if v := _m.RawOutputID; v != nil {
		builder.WriteString("raw_output_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OpenHouseVersions is a parsable slice of OpenHouseVersion.
type OpenHouseVersions []*OpenHouseVersion
