// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/predicate"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/processorcursor"
	"github.com/google/uuid"
)

// ProcessorCursorUpdate is the builder for updating ProcessorCursor entities.
type ProcessorCursorUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessorCursorMutation
}

// Where appends a list predicates to the ProcessorCursorUpdate builder.
func (_u *ProcessorCursorUpdate) Where(ps ...predicate.ProcessorCursor) *ProcessorCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *ProcessorCursorUpdate) SetModifiedAt(v time.Time) *ProcessorCursorUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetLastRawOutputID sets the "last_raw_output_id" field.
func (_u *ProcessorCursorUpdate) SetLastRawOutputID(v uuid.UUID) *ProcessorCursorUpdate {
	_u.mutation.SetLastRawOutputID(v)
	return _u
}

// SetNillableLastRawOutputID sets the "last_raw_output_id" field if the given value is not nil.
func (_u *ProcessorCursorUpdate) SetNillableLastRawOutputID(v *uuid.UUID) *ProcessorCursorUpdate {
	if v != nil {
		_u.SetLastRawOutputID(*v)
	}
	return _u
}

// ClearLastRawOutputID clears the value of the "last_raw_output_id" field.
func (_u *ProcessorCursorUpdate) ClearLastRawOutputID() *ProcessorCursorUpdate {
	_u.mutation.ClearLastRawOutputID()
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *ProcessorCursorUpdate) SetProcessorVersion(v string) *ProcessorCursorUpdate {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *ProcessorCursorUpdate) SetNillableProcessorVersion(v *string) *ProcessorCursorUpdate {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// Mutation returns the ProcessorCursorMutation object of the builder.
func (_u *ProcessorCursorUpdate) Mutation() *ProcessorCursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessorCursorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessorCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessorCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessorCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessorCursorUpdate) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := processorcursor.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

func (_u *ProcessorCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(processorcursor.Table, processorcursor.Columns, sqlgraph.NewFieldSpec(processorcursor.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(processorcursor.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastRawOutputID(); ok {
		_spec.SetField(processorcursor.FieldLastRawOutputID, field.TypeUUID, value)
	}
	if _u.mutation.LastRawOutputIDCleared() {
		_spec.ClearField(processorcursor.FieldLastRawOutputID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(processorcursor.FieldProcessorVersion, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processorcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessorCursorUpdateOne is the builder for updating a single ProcessorCursor entity.
type ProcessorCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessorCursorMutation
}

// SetModifiedAt sets the "modified_at" field.
func (_u *ProcessorCursorUpdateOne) SetModifiedAt(v time.Time) *ProcessorCursorUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetLastRawOutputID sets the "last_raw_output_id" field.
func (_u *ProcessorCursorUpdateOne) SetLastRawOutputID(v uuid.UUID) *ProcessorCursorUpdateOne {
	_u.mutation.SetLastRawOutputID(v)
	return _u
}

// SetNillableLastRawOutputID sets the "last_raw_output_id" field if the given value is not nil.
func (_u *ProcessorCursorUpdateOne) SetNillableLastRawOutputID(v *uuid.UUID) *ProcessorCursorUpdateOne {
	if v != nil {
		_u.SetLastRawOutputID(*v)
	}
	return _u
}

// ClearLastRawOutputID clears the value of the "last_raw_output_id" field.
func (_u *ProcessorCursorUpdateOne) ClearLastRawOutputID() *ProcessorCursorUpdateOne {
	_u.mutation.ClearLastRawOutputID()
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *ProcessorCursorUpdateOne) SetProcessorVersion(v string) *ProcessorCursorUpdateOne {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *ProcessorCursorUpdateOne) SetNillableProcessorVersion(v *string) *ProcessorCursorUpdateOne {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// Mutation returns the ProcessorCursorMutation object of the builder.
func (_u *ProcessorCursorUpdateOne) Mutation() *ProcessorCursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessorCursorUpdate builder.
func (_u *ProcessorCursorUpdateOne) Where(ps ...predicate.ProcessorCursor) *ProcessorCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessorCursorUpdateOne) Select(field string, fields ...string) *ProcessorCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProcessorCursor entity.
func (_u *ProcessorCursorUpdateOne) Save(ctx context.Context) (*ProcessorCursor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessorCursorUpdateOne) SaveX(ctx context.Context) *ProcessorCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessorCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessorCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessorCursorUpdateOne) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := processorcursor.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

func (_u *ProcessorCursorUpdateOne) sqlSave(ctx context.Context) (_node *ProcessorCursor, err error) {
	_spec := sqlgraph.NewUpdateSpec(processorcursor.Table, processorcursor.Columns, sqlgraph.NewFieldSpec(processorcursor.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProcessorCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, processorcursor.FieldID)
		for _, f := range fields {
			if !processorcursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != processorcursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(processorcursor.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastRawOutputID(); ok {
		_spec.SetField(processorcursor.FieldLastRawOutputID, field.TypeUUID, value)
	}
	if _u.mutation.LastRawOutputIDCleared() {
		_spec.ClearField(processorcursor.FieldLastRawOutputID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(processorcursor.FieldProcessorVersion, field.TypeString, value)
	}
	_node = &ProcessorCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{processorcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
