// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/property"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/propertyunittype"
	"github.com/google/uuid"
)

// PropertyUnitTypeCreate is the builder for creating a PropertyUnitType entity.
type PropertyUnitTypeCreate struct {
	config
	mutation *PropertyUnitTypeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PropertyUnitTypeCreate) SetCreatedAt(v time.Time) *PropertyUnitTypeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableCreatedAt(v *time.Time) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *PropertyUnitTypeCreate) SetModifiedAt(v time.Time) *PropertyUnitTypeCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableModifiedAt(v *time.Time) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetSourceModifiedAt sets the "source_modified_at" field.
func (_c *PropertyUnitTypeCreate) SetSourceModifiedAt(v time.Time) *PropertyUnitTypeCreate {
	_c.mutation.SetSourceModifiedAt(v)
	return _c
}

// SetOriginatingSystemName sets the "originating_system_name" field.
func (_c *PropertyUnitTypeCreate) SetOriginatingSystemName(v string) *PropertyUnitTypeCreate {
	_c.mutation.SetOriginatingSystemName(v)
	return _c
}

// SetNillableOriginatingSystemName sets the "originating_system_name" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableOriginatingSystemName(v *string) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetOriginatingSystemName(*v)
	}
	return _c
}

// SetMlgCanView sets the "mlg_can_view" field.
func (_c *PropertyUnitTypeCreate) SetMlgCanView(v bool) *PropertyUnitTypeCreate {
	_c.mutation.SetMlgCanView(v)
	return _c
}

// SetNillableMlgCanView sets the "mlg_can_view" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableMlgCanView(v *bool) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetMlgCanView(*v)
	}
	return _c
}

// SetMlgCanUse sets the "mlg_can_use" field.
func (_c *PropertyUnitTypeCreate) SetMlgCanUse(v []string) *PropertyUnitTypeCreate {
	_c.mutation.SetMlgCanUse(v)
	return _c
}

// SetListingKey sets the "listing_key" field.
func (_c *PropertyUnitTypeCreate) SetListingKey(v string) *PropertyUnitTypeCreate {
	_c.mutation.SetListingKey(v)
	return _c
}

// SetUnitTypeBedsTotal sets the "unit_type_beds_total" field.
func (_c *PropertyUnitTypeCreate) SetUnitTypeBedsTotal(v int16) *PropertyUnitTypeCreate {
	_c.mutation.SetUnitTypeBedsTotal(v)
	return _c
}

// SetNillableUnitTypeBedsTotal sets the "unit_type_beds_total" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableUnitTypeBedsTotal(v *int16) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetUnitTypeBedsTotal(*v)
	}
	return _c
}

// SetUnitTypeFurnished sets the "unit_type_furnished" field.
func (_c *PropertyUnitTypeCreate) SetUnitTypeFurnished(v string) *PropertyUnitTypeCreate {
	_c.mutation.SetUnitTypeFurnished(v)
	return _c
}

// SetNillableUnitTypeFurnished sets the "unit_type_furnished" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableUnitTypeFurnished(v *string) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetUnitTypeFurnished(*v)
	}
	return _c
}

// SetExtendedFields sets the "extended_fields" field.
func (_c *PropertyUnitTypeCreate) SetExtendedFields(v map[string]interface{}) *PropertyUnitTypeCreate {
	_c.mutation.SetExtendedFields(v)
	return _c
}

// SetCurrentVersionID sets the "current_version_id" field.
func (_c *PropertyUnitTypeCreate) SetCurrentVersionID(v uuid.UUID) *PropertyUnitTypeCreate {
	_c.mutation.SetCurrentVersionID(v)
	return _c
}

// SetNillableCurrentVersionID sets the "current_version_id" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableCurrentVersionID(v *uuid.UUID) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetCurrentVersionID(*v)
	}
	return _c
}

// SetParentListingKey sets the "parent_listing_key" field.
func (_c *PropertyUnitTypeCreate) SetParentListingKey(v string) *PropertyUnitTypeCreate {
	_c.mutation.SetParentListingKey(v)
	return _c
}

// SetNillableParentListingKey sets the "parent_listing_key" field if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillableParentListingKey(v *string) *PropertyUnitTypeCreate {
	if v != nil {
		_c.SetParentListingKey(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PropertyUnitTypeCreate) SetID(v string) *PropertyUnitTypeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPropertyID sets the "property" edge to the Property entity by ID.
func (_c *PropertyUnitTypeCreate) SetPropertyID(id string) *PropertyUnitTypeCreate {
	_c.mutation.SetPropertyID(id)
	return _c
}

// SetNillablePropertyID sets the "property" edge to the Property entity by ID if the given value is not nil.
func (_c *PropertyUnitTypeCreate) SetNillablePropertyID(id *string) *PropertyUnitTypeCreate {
	if id != nil {
		_c = _c.SetPropertyID(*id)
	}
	return _c
}

// SetProperty sets the "property" edge to the Property entity.
func (_c *PropertyUnitTypeCreate) SetProperty(v *Property) *PropertyUnitTypeCreate {
	return _c.SetPropertyID(v.ID)
}

// Mutation returns the PropertyUnitTypeMutation object of the builder.
func (_c *PropertyUnitTypeCreate) Mutation() *PropertyUnitTypeMutation {
	return _c.mutation
}

// Save creates the PropertyUnitType in the database.
func (_c *PropertyUnitTypeCreate) Save(ctx context.Context) (*PropertyUnitType, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PropertyUnitTypeCreate) SaveX(ctx context.Context) *PropertyUnitType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyUnitTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyUnitTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PropertyUnitTypeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := propertyunittype.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		v := propertyunittype.DefaultModifiedAt()
		_c.mutation.SetModifiedAt(v)
	}
	if _, ok := _c.mutation.MlgCanView(); !ok {
		v := propertyunittype.DefaultMlgCanView
		_c.mutation.SetMlgCanView(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PropertyUnitTypeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PropertyUnitType.created_at"`)}
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New(`ent: missing required field "PropertyUnitType.modified_at"`)}
	}
	if _, ok := _c.mutation.SourceModifiedAt(); !ok {
		return &ValidationError{Name: "source_modified_at", err: errors.New(`ent: missing required field "PropertyUnitType.source_modified_at"`)}
	}
	if _, ok := _c.mutation.MlgCanView(); !ok {
		return &ValidationError{Name: "mlg_can_view", err: errors.New(`ent: missing required field "PropertyUnitType.mlg_can_view"`)}
	}
	if _, ok := _c.mutation.ListingKey(); !ok {
		return &ValidationError{Name: "listing_key", err: errors.New(`ent: missing required field "PropertyUnitType.listing_key"`)}
	}
	return nil
}

func (_c *PropertyUnitTypeCreate) sqlSave(ctx context.Context) (*PropertyUnitType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PropertyUnitType.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PropertyUnitTypeCreate) createSpec() (*PropertyUnitType, *sqlgraph.CreateSpec) {
	var (
		_node = &PropertyUnitType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(propertyunittype.Table, sqlgraph.NewFieldSpec(propertyunittype.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(propertyunittype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(propertyunittype.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := _c.mutation.SourceModifiedAt(); ok {
		_spec.SetField(propertyunittype.FieldSourceModifiedAt, field.TypeTime, value)
		_node.SourceModifiedAt = value
	}
	if value, ok := _c.mutation.OriginatingSystemName(); ok {
		_spec.SetField(propertyunittype.FieldOriginatingSystemName, field.TypeString, value)
		_node.OriginatingSystemName = &value
	}
	if value, ok := _c.mutation.MlgCanView(); ok {
		_spec.SetField(propertyunittype.FieldMlgCanView, field.TypeBool, value)
		_node.MlgCanView = value
	}
	if value, ok := _c.mutation.MlgCanUse(); ok {
		_spec.SetField(propertyunittype.FieldMlgCanUse, field.TypeJSON, value)
		_node.MlgCanUse = value
	}
	if value, ok := _c.mutation.ListingKey(); ok {
		_spec.SetField(propertyunittype.FieldListingKey, field.TypeString, value)
		_node.ListingKey = value
	}
	if value, ok := _c.mutation.UnitTypeBedsTotal(); ok {
		_spec.SetField(propertyunittype.FieldUnitTypeBedsTotal, field.TypeInt16, value)
		_node.UnitTypeBedsTotal = &value
	}
	if value, ok := _c.mutation.UnitTypeFurnished(); ok {
		_spec.SetField(propertyunittype.FieldUnitTypeFurnished, field.TypeString, value)
		_node.UnitTypeFurnished = &value
	}
	if value, ok := _c.mutation.ExtendedFields(); ok {
		_spec.SetField(propertyunittype.FieldExtendedFields, field.TypeJSON, value)
		_node.ExtendedFields = value
	}
	if value, ok := _c.mutation.CurrentVersionID(); ok {
		_spec.SetField(propertyunittype.FieldCurrentVersionID, field.TypeUUID, value)
		_node.CurrentVersionID = &value
	}
	if nodes := _c.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   propertyunittype.PropertyTable,
			Columns: []string{propertyunittype.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentListingKey = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PropertyUnitTypeCreateBulk is the builder for creating many PropertyUnitType entities in bulk.
type PropertyUnitTypeCreateBulk struct {
	config
	err      error
	builders []*PropertyUnitTypeCreate
}

// Save creates the PropertyUnitType entities in the database.
func (_c *PropertyUnitTypeCreateBulk) Save(ctx context.Context) ([]*PropertyUnitType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PropertyUnitType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PropertyUnitTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PropertyUnitTypeCreateBulk) SaveX(ctx context.Context) []*PropertyUnitType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyUnitTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyUnitTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
