// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/attachmentjob"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/predicate"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/rawoutput"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/syncevent"
)

// RawOutputUpdate is the builder for updating RawOutput entities.
type RawOutputUpdate struct {
	config
	hooks    []Hook
	mutation *RawOutputMutation
}

// Where appends a list predicates to the RawOutputUpdate builder.
func (_u *RawOutputUpdate) Where(ps ...predicate.RawOutput) *RawOutputUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSyncEventID sets the "sync_event_id" field.
func (_u *RawOutputUpdate) SetSyncEventID(v uuid.UUID) *RawOutputUpdate {
	_u.mutation.SetSyncEventID(v)
	return _u
}

// SetNillableSyncEventID sets the "sync_event_id" field if the given value is not nil.
func (_u *RawOutputUpdate) SetNillableSyncEventID(v *uuid.UUID) *RawOutputUpdate {
	if v != nil {
		_u.SetSyncEventID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *RawOutputUpdate) SetResource(v rawoutput.Resource) *RawOutputUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *RawOutputUpdate) SetNillableResource(v *rawoutput.Resource) *RawOutputUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *RawOutputUpdate) SetSourceKey(v string) *RawOutputUpdate {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *RawOutputUpdate) SetNillableSourceKey(v *string) *RawOutputUpdate {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *RawOutputUpdate) SetChangeType(v rawoutput.ChangeType) *RawOutputUpdate {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *RawOutputUpdate) SetNillableChangeType(v *rawoutput.ChangeType) *RawOutputUpdate {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetSourceModifiedAt sets the "source_modified_at" field.
func (_u *RawOutputUpdate) SetSourceModifiedAt(v time.Time) *RawOutputUpdate {
	_u.mutation.SetSourceModifiedAt(v)
	return _u
}

// SetNillableSourceModifiedAt sets the "source_modified_at" field if the given value is not nil.
func (_u *RawOutputUpdate) SetNillableSourceModifiedAt(v *time.Time) *RawOutputUpdate {
	if v != nil {
		_u.SetSourceModifiedAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RawOutputUpdate) SetPayload(v map[string]interface{}) *RawOutputUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetSyncEvent sets the "sync_event" edge to the SyncEvent entity.
func (_u *RawOutputUpdate) SetSyncEvent(v *SyncEvent) *RawOutputUpdate {
	return _u.SetSyncEventID(v.ID)
}

// AddAttachmentJobIDs adds the "attachment_jobs" edge to the AttachmentJob entity by IDs.
func (_u *RawOutputUpdate) AddAttachmentJobIDs(ids ...uuid.UUID) *RawOutputUpdate {
	_u.mutation.AddAttachmentJobIDs(ids...)
	return _u
}

// AddAttachmentJobs adds the "attachment_jobs" edges to the AttachmentJob entity.
func (_u *RawOutputUpdate) AddAttachmentJobs(v ...*AttachmentJob) *RawOutputUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentJobIDs(ids...)
}

// Mutation returns the RawOutputMutation object of the builder.
func (_u *RawOutputUpdate) Mutation() *RawOutputMutation {
	return _u.mutation
}

// ClearSyncEvent clears the "sync_event" edge to the SyncEvent entity.
func (_u *RawOutputUpdate) ClearSyncEvent() *RawOutputUpdate {
	_u.mutation.ClearSyncEvent()
	return _u
}

// ClearAttachmentJobs clears all "attachment_jobs" edges to the AttachmentJob entity.
func (_u *RawOutputUpdate) ClearAttachmentJobs() *RawOutputUpdate {
	_u.mutation.ClearAttachmentJobs()
	return _u
}

// RemoveAttachmentJobIDs removes the "attachment_jobs" edge to AttachmentJob entities by IDs.
func (_u *RawOutputUpdate) RemoveAttachmentJobIDs(ids ...uuid.UUID) *RawOutputUpdate {
	_u.mutation.RemoveAttachmentJobIDs(ids...)
	return _u
}

// RemoveAttachmentJobs removes "attachment_jobs" edges to AttachmentJob entities.
func (_u *RawOutputUpdate) RemoveAttachmentJobs(v ...*AttachmentJob) *RawOutputUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RawOutputUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RawOutputUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RawOutputUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RawOutputUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RawOutputUpdate) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := rawoutput.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "RawOutput.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := rawoutput.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "RawOutput.change_type": %w`, err)}
		}
	}
	if _u.mutation.SyncEventCleared() && len(_u.mutation.SyncEventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RawOutput.sync_event"`)
	}
	return nil
}

func (_u *RawOutputUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rawoutput.Table, rawoutput.Columns, sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(rawoutput.FieldResource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(rawoutput.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(rawoutput.FieldChangeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceModifiedAt(); ok {
		_spec.SetField(rawoutput.FieldSourceModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(rawoutput.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.SyncEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rawoutput.SyncEventTable,
			Columns: []string{rawoutput.SyncEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rawoutput.SyncEventTable,
			Columns: []string{rawoutput.SyncEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentJobsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rawoutput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RawOutputUpdateOne is the builder for updating a single RawOutput entity.
type RawOutputUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RawOutputMutation
}

// SetSyncEventID sets the "sync_event_id" field.
func (_u *RawOutputUpdateOne) SetSyncEventID(v uuid.UUID) *RawOutputUpdateOne {
	_u.mutation.SetSyncEventID(v)
	return _u
}

// SetNillableSyncEventID sets the "sync_event_id" field if the given value is not nil.
func (_u *RawOutputUpdateOne) SetNillableSyncEventID(v *uuid.UUID) *RawOutputUpdateOne {
	if v != nil {
		_u.SetSyncEventID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *RawOutputUpdateOne) SetResource(v rawoutput.Resource) *RawOutputUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *RawOutputUpdateOne) SetNillableResource(v *rawoutput.Resource) *RawOutputUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *RawOutputUpdateOne) SetSourceKey(v string) *RawOutputUpdateOne {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *RawOutputUpdateOne) SetNillableSourceKey(v *string) *RawOutputUpdateOne {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// SetChangeType sets the "change_type" field.
func (_u *RawOutputUpdateOne) SetChangeType(v rawoutput.ChangeType) *RawOutputUpdateOne {
	_u.mutation.SetChangeType(v)
	return _u
}

// SetNillableChangeType sets the "change_type" field if the given value is not nil.
func (_u *RawOutputUpdateOne) SetNillableChangeType(v *rawoutput.ChangeType) *RawOutputUpdateOne {
	if v != nil {
		_u.SetChangeType(*v)
	}
	return _u
}

// SetSourceModifiedAt sets the "source_modified_at" field.
func (_u *RawOutputUpdateOne) SetSourceModifiedAt(v time.Time) *RawOutputUpdateOne {
	_u.mutation.SetSourceModifiedAt(v)
	return _u
}

// SetNillableSourceModifiedAt sets the "source_modified_at" field if the given value is not nil.
func (_u *RawOutputUpdateOne) SetNillableSourceModifiedAt(v *time.Time) *RawOutputUpdateOne {
	if v != nil {
		_u.SetSourceModifiedAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RawOutputUpdateOne) SetPayload(v map[string]interface{}) *RawOutputUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetSyncEvent sets the "sync_event" edge to the SyncEvent entity.
func (_u *RawOutputUpdateOne) SetSyncEvent(v *SyncEvent) *RawOutputUpdateOne {
	return _u.SetSyncEventID(v.ID)
}

// AddAttachmentJobIDs adds the "attachment_jobs" edge to the AttachmentJob entity by IDs.
func (_u *RawOutputUpdateOne) AddAttachmentJobIDs(ids ...uuid.UUID) *RawOutputUpdateOne {
	_u.mutation.AddAttachmentJobIDs(ids...)
	return _u
}

// AddAttachmentJobs adds the "attachment_jobs" edges to the AttachmentJob entity.
func (_u *RawOutputUpdateOne) AddAttachmentJobs(v ...*AttachmentJob) *RawOutputUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentJobIDs(ids...)
}

// Mutation returns the RawOutputMutation object of the builder.
func (_u *RawOutputUpdateOne) Mutation() *RawOutputMutation {
	return _u.mutation
}

// ClearSyncEvent clears the "sync_event" edge to the SyncEvent entity.
func (_u *RawOutputUpdateOne) ClearSyncEvent() *RawOutputUpdateOne {
	_u.mutation.ClearSyncEvent()
	return _u
}

// ClearAttachmentJobs clears all "attachment_jobs" edges to the AttachmentJob entity.
func (_u *RawOutputUpdateOne) ClearAttachmentJobs() *RawOutputUpdateOne {
	_u.mutation.ClearAttachmentJobs()
	return _u
}

// RemoveAttachmentJobIDs removes the "attachment_jobs" edge to AttachmentJob entities by IDs.
func (_u *RawOutputUpdateOne) RemoveAttachmentJobIDs(ids ...uuid.UUID) *RawOutputUpdateOne {
	_u.mutation.RemoveAttachmentJobIDs(ids...)
	return _u
}

// RemoveAttachmentJobs removes "attachment_jobs" edges to AttachmentJob entities.
func (_u *RawOutputUpdateOne) RemoveAttachmentJobs(v ...*AttachmentJob) *RawOutputUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentJobIDs(ids...)
}

// Where appends a list predicates to the RawOutputUpdate builder.
func (_u *RawOutputUpdateOne) Where(ps ...predicate.RawOutput) *RawOutputUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RawOutputUpdateOne) Select(field string, fields ...string) *RawOutputUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RawOutput entity.
func (_u *RawOutputUpdateOne) Save(ctx context.Context) (*RawOutput, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RawOutputUpdateOne) SaveX(ctx context.Context) *RawOutput {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RawOutputUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RawOutputUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RawOutputUpdateOne) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := rawoutput.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "RawOutput.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeType(); ok {
		if err := rawoutput.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "RawOutput.change_type": %w`, err)}
		}
	}
	if _u.mutation.SyncEventCleared() && len(_u.mutation.SyncEventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RawOutput.sync_event"`)
	}
	return nil
}

func (_u *RawOutputUpdateOne) sqlSave(ctx context.Context) (_node *RawOutput, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rawoutput.Table, rawoutput.Columns, sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RawOutput.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rawoutput.FieldID)
		for _, f := range fields {
			if !rawoutput.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rawoutput.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(rawoutput.FieldResource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(rawoutput.FieldSourceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeType(); ok {
		_spec.SetField(rawoutput.FieldChangeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceModifiedAt(); ok {
		_spec.SetField(rawoutput.FieldSourceModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(rawoutput.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.SyncEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rawoutput.SyncEventTable,
			Columns: []string{rawoutput.SyncEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rawoutput.SyncEventTable,
			Columns: []string{rawoutput.SyncEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentJobsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rawoutput.AttachmentJobsTable,
			Columns: []string{rawoutput.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RawOutput{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rawoutput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
