// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/attachment"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/attachmentjob"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/lookup"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/media"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/mediaversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/member"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/memberversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/office"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/officeversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/openhouse"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/openhouseversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/processorcursor"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/property"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/propertyroom"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/propertyroomversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/propertyunittype"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/propertyunittypeversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/propertyversion"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/rawoutput"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/schema"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/sourcesystem"
	"github.com/lunarhue/website-highpointe/packages/mls-grid-sync/ent/syncevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentMixin := schema.Attachment{}.Mixin()
	attachmentMixinFields0 := attachmentMixin[0].Fields()
	_ = attachmentMixinFields0
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescCreatedAt is the schema descriptor for created_at field.
	attachmentDescCreatedAt := attachmentMixinFields0[0].Descriptor()
	// attachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachment.DefaultCreatedAt = attachmentDescCreatedAt.Default.(func() time.Time)
	// attachmentDescModifiedAt is the schema descriptor for modified_at field.
	attachmentDescModifiedAt := attachmentMixinFields0[1].Descriptor()
	// attachment.DefaultModifiedAt holds the default value on creation for the modified_at field.
	attachment.DefaultModifiedAt = attachmentDescModifiedAt.Default.(func() time.Time)
	// attachment.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	attachment.UpdateDefaultModifiedAt = attachmentDescModifiedAt.UpdateDefault.(func() time.Time)
	// attachmentDescID is the schema descriptor for id field.
	attachmentDescID := attachmentFields[0].Descriptor()
	// attachment.DefaultID holds the default value on creation for the id field.
	attachment.DefaultID = attachmentDescID.Default.(func() uuid.UUID)
	attachmentjobMixin := schema.AttachmentJob{}.Mixin()
	attachmentjobMixinFields0 := attachmentjobMixin[0].Fields()
	_ = attachmentjobMixinFields0
	attachmentjobFields := schema.AttachmentJob{}.Fields()
	_ = attachmentjobFields
	// attachmentjobDescCreatedAt is the schema descriptor for created_at field.
	attachmentjobDescCreatedAt := attachmentjobMixinFields0[0].Descriptor()
	// attachmentjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachmentjob.DefaultCreatedAt = attachmentjobDescCreatedAt.Default.(func() time.Time)
	// attachmentjobDescModifiedAt is the schema descriptor for modified_at field.
	attachmentjobDescModifiedAt := attachmentjobMixinFields0[1].Descriptor()
	// attachmentjob.DefaultModifiedAt holds the default value on creation for the modified_at field.
	attachmentjob.DefaultModifiedAt = attachmentjobDescModifiedAt.Default.(func() time.Time)
	// attachmentjob.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	attachmentjob.UpdateDefaultModifiedAt = attachmentjobDescModifiedAt.UpdateDefault.(func() time.Time)
	// attachmentjobDescAttemptCount is the schema descriptor for attempt_count field.
	attachmentjobDescAttemptCount := attachmentjobFields[6].Descriptor()
	// attachmentjob.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	attachmentjob.DefaultAttemptCount = attachmentjobDescAttemptCount.Default.(int)
	// attachmentjobDescID is the schema descriptor for id field.
	attachmentjobDescID := attachmentjobFields[0].Descriptor()
	// attachmentjob.DefaultID holds the default value on creation for the id field.
	attachmentjob.DefaultID = attachmentjobDescID.Default.(func() uuid.UUID)
	lookupMixin := schema.Lookup{}.Mixin()
	lookupMixinFields0 := lookupMixin[0].Fields()
	_ = lookupMixinFields0
	lookupMixinFields1 := lookupMixin[1].Fields()
	_ = lookupMixinFields1
	lookupFields := schema.Lookup{}.Fields()
	_ = lookupFields
	// lookupDescCreatedAt is the schema descriptor for created_at field.
	lookupDescCreatedAt := lookupMixinFields0[0].Descriptor()
	// lookup.DefaultCreatedAt holds the default value on creation for the created_at field.
	lookup.DefaultCreatedAt = lookupDescCreatedAt.Default.(func() time.Time)
	// lookupDescModifiedAt is the schema descriptor for modified_at field.
	lookupDescModifiedAt := lookupMixinFields0[1].Descriptor()
	// lookup.DefaultModifiedAt holds the default value on creation for the modified_at field.
	lookup.DefaultModifiedAt = lookupDescModifiedAt.Default.(func() time.Time)
	// lookup.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	lookup.UpdateDefaultModifiedAt = lookupDescModifiedAt.UpdateDefault.(func() time.Time)
	// lookupDescMlgCanView is the schema descriptor for mlg_can_view field.
	lookupDescMlgCanView := lookupMixinFields1[2].Descriptor()
	// lookup.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	lookup.DefaultMlgCanView = lookupDescMlgCanView.Default.(bool)
	mediaMixin := schema.Media{}.Mixin()
	mediaMixinFields0 := mediaMixin[0].Fields()
	_ = mediaMixinFields0
	mediaMixinFields1 := mediaMixin[1].Fields()
	_ = mediaMixinFields1
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaMixinFields0[0].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescModifiedAt is the schema descriptor for modified_at field.
	mediaDescModifiedAt := mediaMixinFields0[1].Descriptor()
	// media.DefaultModifiedAt holds the default value on creation for the modified_at field.
	media.DefaultModifiedAt = mediaDescModifiedAt.Default.(func() time.Time)
	// media.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	media.UpdateDefaultModifiedAt = mediaDescModifiedAt.UpdateDefault.(func() time.Time)
	// mediaDescMlgCanView is the schema descriptor for mlg_can_view field.
	mediaDescMlgCanView := mediaMixinFields1[2].Descriptor()
	// media.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	media.DefaultMlgCanView = mediaDescMlgCanView.Default.(bool)
	mediaversionMixin := schema.MediaVersion{}.Mixin()
	mediaversionMixinFields0 := mediaversionMixin[0].Fields()
	_ = mediaversionMixinFields0
	mediaversionMixinFields1 := mediaversionMixin[1].Fields()
	_ = mediaversionMixinFields1
	mediaversionFields := schema.MediaVersion{}.Fields()
	_ = mediaversionFields
	// mediaversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	mediaversionDescMlgCanView := mediaversionMixinFields1[2].Descriptor()
	// mediaversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	mediaversion.DefaultMlgCanView = mediaversionDescMlgCanView.Default.(bool)
	// mediaversionDescID is the schema descriptor for id field.
	mediaversionDescID := mediaversionMixinFields0[0].Descriptor()
	// mediaversion.DefaultID holds the default value on creation for the id field.
	mediaversion.DefaultID = mediaversionDescID.Default.(func() string)
	memberMixin := schema.Member{}.Mixin()
	memberMixinFields0 := memberMixin[0].Fields()
	_ = memberMixinFields0
	memberMixinFields1 := memberMixin[1].Fields()
	_ = memberMixinFields1
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberMixinFields0[0].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
	// memberDescModifiedAt is the schema descriptor for modified_at field.
	memberDescModifiedAt := memberMixinFields0[1].Descriptor()
	// member.DefaultModifiedAt holds the default value on creation for the modified_at field.
	member.DefaultModifiedAt = memberDescModifiedAt.Default.(func() time.Time)
	// member.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	member.UpdateDefaultModifiedAt = memberDescModifiedAt.UpdateDefault.(func() time.Time)
	// memberDescMlgCanView is the schema descriptor for mlg_can_view field.
	memberDescMlgCanView := memberMixinFields1[2].Descriptor()
	// member.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	member.DefaultMlgCanView = memberDescMlgCanView.Default.(bool)
	memberversionMixin := schema.MemberVersion{}.Mixin()
	memberversionMixinFields0 := memberversionMixin[0].Fields()
	_ = memberversionMixinFields0
	memberversionMixinFields1 := memberversionMixin[1].Fields()
	_ = memberversionMixinFields1
	memberversionFields := schema.MemberVersion{}.Fields()
	_ = memberversionFields
	// memberversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	memberversionDescMlgCanView := memberversionMixinFields1[2].Descriptor()
	// memberversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	memberversion.DefaultMlgCanView = memberversionDescMlgCanView.Default.(bool)
	// memberversionDescID is the schema descriptor for id field.
	memberversionDescID := memberversionMixinFields0[0].Descriptor()
	// memberversion.DefaultID holds the default value on creation for the id field.
	memberversion.DefaultID = memberversionDescID.Default.(func() string)
	officeMixin := schema.Office{}.Mixin()
	officeMixinFields0 := officeMixin[0].Fields()
	_ = officeMixinFields0
	officeMixinFields1 := officeMixin[1].Fields()
	_ = officeMixinFields1
	officeFields := schema.Office{}.Fields()
	_ = officeFields
	// officeDescCreatedAt is the schema descriptor for created_at field.
	officeDescCreatedAt := officeMixinFields0[0].Descriptor()
	// office.DefaultCreatedAt holds the default value on creation for the created_at field.
	office.DefaultCreatedAt = officeDescCreatedAt.Default.(func() time.Time)
	// officeDescModifiedAt is the schema descriptor for modified_at field.
	officeDescModifiedAt := officeMixinFields0[1].Descriptor()
	// office.DefaultModifiedAt holds the default value on creation for the modified_at field.
	office.DefaultModifiedAt = officeDescModifiedAt.Default.(func() time.Time)
	// office.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	office.UpdateDefaultModifiedAt = officeDescModifiedAt.UpdateDefault.(func() time.Time)
	// officeDescMlgCanView is the schema descriptor for mlg_can_view field.
	officeDescMlgCanView := officeMixinFields1[2].Descriptor()
	// office.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	office.DefaultMlgCanView = officeDescMlgCanView.Default.(bool)
	officeversionMixin := schema.OfficeVersion{}.Mixin()
	officeversionMixinFields0 := officeversionMixin[0].Fields()
	_ = officeversionMixinFields0
	officeversionMixinFields1 := officeversionMixin[1].Fields()
	_ = officeversionMixinFields1
	officeversionFields := schema.OfficeVersion{}.Fields()
	_ = officeversionFields
	// officeversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	officeversionDescMlgCanView := officeversionMixinFields1[2].Descriptor()
	// officeversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	officeversion.DefaultMlgCanView = officeversionDescMlgCanView.Default.(bool)
	// officeversionDescID is the schema descriptor for id field.
	officeversionDescID := officeversionMixinFields0[0].Descriptor()
	// officeversion.DefaultID holds the default value on creation for the id field.
	officeversion.DefaultID = officeversionDescID.Default.(func() string)
	openhouseMixin := schema.OpenHouse{}.Mixin()
	openhouseMixinFields0 := openhouseMixin[0].Fields()
	_ = openhouseMixinFields0
	openhouseMixinFields1 := openhouseMixin[1].Fields()
	_ = openhouseMixinFields1
	openhouseFields := schema.OpenHouse{}.Fields()
	_ = openhouseFields
	// openhouseDescCreatedAt is the schema descriptor for created_at field.
	openhouseDescCreatedAt := openhouseMixinFields0[0].Descriptor()
	// openhouse.DefaultCreatedAt holds the default value on creation for the created_at field.
	openhouse.DefaultCreatedAt = openhouseDescCreatedAt.Default.(func() time.Time)
	// openhouseDescModifiedAt is the schema descriptor for modified_at field.
	openhouseDescModifiedAt := openhouseMixinFields0[1].Descriptor()
	// openhouse.DefaultModifiedAt holds the default value on creation for the modified_at field.
	openhouse.DefaultModifiedAt = openhouseDescModifiedAt.Default.(func() time.Time)
	// openhouse.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	openhouse.UpdateDefaultModifiedAt = openhouseDescModifiedAt.UpdateDefault.(func() time.Time)
	// openhouseDescMlgCanView is the schema descriptor for mlg_can_view field.
	openhouseDescMlgCanView := openhouseMixinFields1[2].Descriptor()
	// openhouse.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	openhouse.DefaultMlgCanView = openhouseDescMlgCanView.Default.(bool)
	openhouseversionMixin := schema.OpenHouseVersion{}.Mixin()
	openhouseversionMixinFields0 := openhouseversionMixin[0].Fields()
	_ = openhouseversionMixinFields0
	openhouseversionMixinFields1 := openhouseversionMixin[1].Fields()
	_ = openhouseversionMixinFields1
	openhouseversionFields := schema.OpenHouseVersion{}.Fields()
	_ = openhouseversionFields
	// openhouseversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	openhouseversionDescMlgCanView := openhouseversionMixinFields1[2].Descriptor()
	// openhouseversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	openhouseversion.DefaultMlgCanView = openhouseversionDescMlgCanView.Default.(bool)
	// openhouseversionDescID is the schema descriptor for id field.
	openhouseversionDescID := openhouseversionMixinFields0[0].Descriptor()
	// openhouseversion.DefaultID holds the default value on creation for the id field.
	openhouseversion.DefaultID = openhouseversionDescID.Default.(func() string)
	processorcursorMixin := schema.ProcessorCursor{}.Mixin()
	processorcursorMixinFields0 := processorcursorMixin[0].Fields()
	_ = processorcursorMixinFields0
	processorcursorFields := schema.ProcessorCursor{}.Fields()
	_ = processorcursorFields
	// processorcursorDescCreatedAt is the schema descriptor for created_at field.
	processorcursorDescCreatedAt := processorcursorMixinFields0[0].Descriptor()
	// processorcursor.DefaultCreatedAt holds the default value on creation for the created_at field.
	processorcursor.DefaultCreatedAt = processorcursorDescCreatedAt.Default.(func() time.Time)
	// processorcursorDescModifiedAt is the schema descriptor for modified_at field.
	processorcursorDescModifiedAt := processorcursorMixinFields0[1].Descriptor()
	// processorcursor.DefaultModifiedAt holds the default value on creation for the modified_at field.
	processorcursor.DefaultModifiedAt = processorcursorDescModifiedAt.Default.(func() time.Time)
	// processorcursor.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	processorcursor.UpdateDefaultModifiedAt = processorcursorDescModifiedAt.UpdateDefault.(func() time.Time)
	// processorcursorDescID is the schema descriptor for id field.
	processorcursorDescID := processorcursorFields[0].Descriptor()
	// processorcursor.DefaultID holds the default value on creation for the id field.
	processorcursor.DefaultID = processorcursorDescID.Default.(func() uuid.UUID)
	propertyMixin := schema.Property{}.Mixin()
	propertyMixinFields0 := propertyMixin[0].Fields()
	_ = propertyMixinFields0
	propertyMixinFields1 := propertyMixin[1].Fields()
	_ = propertyMixinFields1
	propertyFields := schema.Property{}.Fields()
	_ = propertyFields
	// propertyDescCreatedAt is the schema descriptor for created_at field.
	propertyDescCreatedAt := propertyMixinFields0[0].Descriptor()
	// property.DefaultCreatedAt holds the default value on creation for the created_at field.
	property.DefaultCreatedAt = propertyDescCreatedAt.Default.(func() time.Time)
	// propertyDescModifiedAt is the schema descriptor for modified_at field.
	propertyDescModifiedAt := propertyMixinFields0[1].Descriptor()
	// property.DefaultModifiedAt holds the default value on creation for the modified_at field.
	property.DefaultModifiedAt = propertyDescModifiedAt.Default.(func() time.Time)
	// property.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	property.UpdateDefaultModifiedAt = propertyDescModifiedAt.UpdateDefault.(func() time.Time)
	// propertyDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyDescMlgCanView := propertyMixinFields1[2].Descriptor()
	// property.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	property.DefaultMlgCanView = propertyDescMlgCanView.Default.(bool)
	propertyroomMixin := schema.PropertyRoom{}.Mixin()
	propertyroomMixinFields0 := propertyroomMixin[0].Fields()
	_ = propertyroomMixinFields0
	propertyroomMixinFields1 := propertyroomMixin[1].Fields()
	_ = propertyroomMixinFields1
	propertyroomFields := schema.PropertyRoom{}.Fields()
	_ = propertyroomFields
	// propertyroomDescCreatedAt is the schema descriptor for created_at field.
	propertyroomDescCreatedAt := propertyroomMixinFields0[0].Descriptor()
	// propertyroom.DefaultCreatedAt holds the default value on creation for the created_at field.
	propertyroom.DefaultCreatedAt = propertyroomDescCreatedAt.Default.(func() time.Time)
	// propertyroomDescModifiedAt is the schema descriptor for modified_at field.
	propertyroomDescModifiedAt := propertyroomMixinFields0[1].Descriptor()
	// propertyroom.DefaultModifiedAt holds the default value on creation for the modified_at field.
	propertyroom.DefaultModifiedAt = propertyroomDescModifiedAt.Default.(func() time.Time)
	// propertyroom.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	propertyroom.UpdateDefaultModifiedAt = propertyroomDescModifiedAt.UpdateDefault.(func() time.Time)
	// propertyroomDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyroomDescMlgCanView := propertyroomMixinFields1[2].Descriptor()
	// propertyroom.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	propertyroom.DefaultMlgCanView = propertyroomDescMlgCanView.Default.(bool)
	propertyroomversionMixin := schema.PropertyRoomVersion{}.Mixin()
	propertyroomversionMixinFields0 := propertyroomversionMixin[0].Fields()
	_ = propertyroomversionMixinFields0
	propertyroomversionMixinFields1 := propertyroomversionMixin[1].Fields()
	_ = propertyroomversionMixinFields1
	propertyroomversionFields := schema.PropertyRoomVersion{}.Fields()
	_ = propertyroomversionFields
	// propertyroomversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyroomversionDescMlgCanView := propertyroomversionMixinFields1[2].Descriptor()
	// propertyroomversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	propertyroomversion.DefaultMlgCanView = propertyroomversionDescMlgCanView.Default.(bool)
	// propertyroomversionDescID is the schema descriptor for id field.
	propertyroomversionDescID := propertyroomversionMixinFields0[0].Descriptor()
	// propertyroomversion.DefaultID holds the default value on creation for the id field.
	propertyroomversion.DefaultID = propertyroomversionDescID.Default.(func() string)
	propertyunittypeMixin := schema.PropertyUnitType{}.Mixin()
	propertyunittypeMixinFields0 := propertyunittypeMixin[0].Fields()
	_ = propertyunittypeMixinFields0
	propertyunittypeMixinFields1 := propertyunittypeMixin[1].Fields()
	_ = propertyunittypeMixinFields1
	propertyunittypeFields := schema.PropertyUnitType{}.Fields()
	_ = propertyunittypeFields
	// propertyunittypeDescCreatedAt is the schema descriptor for created_at field.
	propertyunittypeDescCreatedAt := propertyunittypeMixinFields0[0].Descriptor()
	// propertyunittype.DefaultCreatedAt holds the default value on creation for the created_at field.
	propertyunittype.DefaultCreatedAt = propertyunittypeDescCreatedAt.Default.(func() time.Time)
	// propertyunittypeDescModifiedAt is the schema descriptor for modified_at field.
	propertyunittypeDescModifiedAt := propertyunittypeMixinFields0[1].Descriptor()
	// propertyunittype.DefaultModifiedAt holds the default value on creation for the modified_at field.
	propertyunittype.DefaultModifiedAt = propertyunittypeDescModifiedAt.Default.(func() time.Time)
	// propertyunittype.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	propertyunittype.UpdateDefaultModifiedAt = propertyunittypeDescModifiedAt.UpdateDefault.(func() time.Time)
	// propertyunittypeDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyunittypeDescMlgCanView := propertyunittypeMixinFields1[2].Descriptor()
	// propertyunittype.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	propertyunittype.DefaultMlgCanView = propertyunittypeDescMlgCanView.Default.(bool)
	propertyunittypeversionMixin := schema.PropertyUnitTypeVersion{}.Mixin()
	propertyunittypeversionMixinFields0 := propertyunittypeversionMixin[0].Fields()
	_ = propertyunittypeversionMixinFields0
	propertyunittypeversionMixinFields1 := propertyunittypeversionMixin[1].Fields()
	_ = propertyunittypeversionMixinFields1
	propertyunittypeversionFields := schema.PropertyUnitTypeVersion{}.Fields()
	_ = propertyunittypeversionFields
	// propertyunittypeversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyunittypeversionDescMlgCanView := propertyunittypeversionMixinFields1[2].Descriptor()
	// propertyunittypeversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	propertyunittypeversion.DefaultMlgCanView = propertyunittypeversionDescMlgCanView.Default.(bool)
	// propertyunittypeversionDescID is the schema descriptor for id field.
	propertyunittypeversionDescID := propertyunittypeversionMixinFields0[0].Descriptor()
	// propertyunittypeversion.DefaultID holds the default value on creation for the id field.
	propertyunittypeversion.DefaultID = propertyunittypeversionDescID.Default.(func() string)
	propertyversionMixin := schema.PropertyVersion{}.Mixin()
	propertyversionMixinFields0 := propertyversionMixin[0].Fields()
	_ = propertyversionMixinFields0
	propertyversionMixinFields1 := propertyversionMixin[1].Fields()
	_ = propertyversionMixinFields1
	propertyversionFields := schema.PropertyVersion{}.Fields()
	_ = propertyversionFields
	// propertyversionDescMlgCanView is the schema descriptor for mlg_can_view field.
	propertyversionDescMlgCanView := propertyversionMixinFields1[2].Descriptor()
	// propertyversion.DefaultMlgCanView holds the default value on creation for the mlg_can_view field.
	propertyversion.DefaultMlgCanView = propertyversionDescMlgCanView.Default.(bool)
	// propertyversionDescID is the schema descriptor for id field.
	propertyversionDescID := propertyversionMixinFields0[0].Descriptor()
	// propertyversion.DefaultID holds the default value on creation for the id field.
	propertyversion.DefaultID = propertyversionDescID.Default.(func() string)
	rawoutputFields := schema.RawOutput{}.Fields()
	_ = rawoutputFields
	// rawoutputDescCreatedAt is the schema descriptor for created_at field.
	rawoutputDescCreatedAt := rawoutputFields[7].Descriptor()
	// rawoutput.DefaultCreatedAt holds the default value on creation for the created_at field.
	rawoutput.DefaultCreatedAt = rawoutputDescCreatedAt.Default.(func() time.Time)
	// rawoutputDescID is the schema descriptor for id field.
	rawoutputDescID := rawoutputFields[0].Descriptor()
	// rawoutput.DefaultID holds the default value on creation for the id field.
	rawoutput.DefaultID = rawoutputDescID.Default.(func() uuid.UUID)
	sourcesystemMixin := schema.SourceSystem{}.Mixin()
	sourcesystemMixinFields0 := sourcesystemMixin[0].Fields()
	_ = sourcesystemMixinFields0
	sourcesystemFields := schema.SourceSystem{}.Fields()
	_ = sourcesystemFields
	// sourcesystemDescCreatedAt is the schema descriptor for created_at field.
	sourcesystemDescCreatedAt := sourcesystemMixinFields0[0].Descriptor()
	// sourcesystem.DefaultCreatedAt holds the default value on creation for the created_at field.
	sourcesystem.DefaultCreatedAt = sourcesystemDescCreatedAt.Default.(func() time.Time)
	// sourcesystemDescModifiedAt is the schema descriptor for modified_at field.
	sourcesystemDescModifiedAt := sourcesystemMixinFields0[1].Descriptor()
	// sourcesystem.DefaultModifiedAt holds the default value on creation for the modified_at field.
	sourcesystem.DefaultModifiedAt = sourcesystemDescModifiedAt.Default.(func() time.Time)
	// sourcesystem.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	sourcesystem.UpdateDefaultModifiedAt = sourcesystemDescModifiedAt.UpdateDefault.(func() time.Time)
	synceventMixin := schema.SyncEvent{}.Mixin()
	synceventMixinFields0 := synceventMixin[0].Fields()
	_ = synceventMixinFields0
	synceventFields := schema.SyncEvent{}.Fields()
	_ = synceventFields
	// synceventDescCreatedAt is the schema descriptor for created_at field.
	synceventDescCreatedAt := synceventMixinFields0[0].Descriptor()
	// syncevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	syncevent.DefaultCreatedAt = synceventDescCreatedAt.Default.(func() time.Time)
	// synceventDescModifiedAt is the schema descriptor for modified_at field.
	synceventDescModifiedAt := synceventMixinFields0[1].Descriptor()
	// syncevent.DefaultModifiedAt holds the default value on creation for the modified_at field.
	syncevent.DefaultModifiedAt = synceventDescModifiedAt.Default.(func() time.Time)
	// syncevent.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	syncevent.UpdateDefaultModifiedAt = synceventDescModifiedAt.UpdateDefault.(func() time.Time)
	// synceventDescRecordCount is the schema descriptor for record_count field.
	synceventDescRecordCount := synceventFields[9].Descriptor()
	// syncevent.DefaultRecordCount holds the default value on creation for the record_count field.
	syncevent.DefaultRecordCount = synceventDescRecordCount.Default.(int)
	// synceventDescID is the schema descriptor for id field.
	synceventDescID := synceventFields[0].Descriptor()
	// syncevent.DefaultID holds the default value on creation for the id field.
	syncevent.DefaultID = synceventDescID.Default.(func() uuid.UUID)
}
