// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/predicate"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/sourcesystem"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/syncevent"
	"github.com/google/uuid"
)

// SourceSystemUpdate is the builder for updating SourceSystem entities.
type SourceSystemUpdate struct {
	config
	hooks    []Hook
	mutation *SourceSystemMutation
}

// Where appends a list predicates to the SourceSystemUpdate builder.
func (_u *SourceSystemUpdate) Where(ps ...predicate.SourceSystem) *SourceSystemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *SourceSystemUpdate) SetModifiedAt(v time.Time) *SourceSystemUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetSourceSystemName sets the "source_system_name" field.
func (_u *SourceSystemUpdate) SetSourceSystemName(v string) *SourceSystemUpdate {
	_u.mutation.SetSourceSystemName(v)
	return _u
}

// SetNillableSourceSystemName sets the "source_system_name" field if the given value is not nil.
func (_u *SourceSystemUpdate) SetNillableSourceSystemName(v *string) *SourceSystemUpdate {
	if v != nil {
		_u.SetSourceSystemName(*v)
	}
	return _u
}

// AddSyncEventIDs adds the "sync_events" edge to the SyncEvent entity by IDs.
func (_u *SourceSystemUpdate) AddSyncEventIDs(ids ...uuid.UUID) *SourceSystemUpdate {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SyncEvent entity.
func (_u *SourceSystemUpdate) AddSyncEvents(v ...*SyncEvent) *SourceSystemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// Mutation returns the SourceSystemMutation object of the builder.
func (_u *SourceSystemUpdate) Mutation() *SourceSystemMutation {
	return _u.mutation
}

// ClearSyncEvents clears all "sync_events" edges to the SyncEvent entity.
func (_u *SourceSystemUpdate) ClearSyncEvents() *SourceSystemUpdate {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SyncEvent entities by IDs.
func (_u *SourceSystemUpdate) RemoveSyncEventIDs(ids ...uuid.UUID) *SourceSystemUpdate {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SyncEvent entities.
func (_u *SourceSystemUpdate) RemoveSyncEvents(v ...*SyncEvent) *SourceSystemUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceSystemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceSystemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceSystemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceSystemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceSystemUpdate) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := sourcesystem.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

func (_u *SourceSystemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcesystem.Table, sourcesystem.Columns, sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(sourcesystem.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceSystemName(); ok {
		_spec.SetField(sourcesystem.FieldSourceSystemName, field.TypeString, value)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcesystem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceSystemUpdateOne is the builder for updating a single SourceSystem entity.
type SourceSystemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceSystemMutation
}

// SetModifiedAt sets the "modified_at" field.
func (_u *SourceSystemUpdateOne) SetModifiedAt(v time.Time) *SourceSystemUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetSourceSystemName sets the "source_system_name" field.
func (_u *SourceSystemUpdateOne) SetSourceSystemName(v string) *SourceSystemUpdateOne {
	_u.mutation.SetSourceSystemName(v)
	return _u
}

// SetNillableSourceSystemName sets the "source_system_name" field if the given value is not nil.
func (_u *SourceSystemUpdateOne) SetNillableSourceSystemName(v *string) *SourceSystemUpdateOne {
	if v != nil {
		_u.SetSourceSystemName(*v)
	}
	return _u
}

// AddSyncEventIDs adds the "sync_events" edge to the SyncEvent entity by IDs.
func (_u *SourceSystemUpdateOne) AddSyncEventIDs(ids ...uuid.UUID) *SourceSystemUpdateOne {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SyncEvent entity.
func (_u *SourceSystemUpdateOne) AddSyncEvents(v ...*SyncEvent) *SourceSystemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// Mutation returns the SourceSystemMutation object of the builder.
func (_u *SourceSystemUpdateOne) Mutation() *SourceSystemMutation {
	return _u.mutation
}

// ClearSyncEvents clears all "sync_events" edges to the SyncEvent entity.
func (_u *SourceSystemUpdateOne) ClearSyncEvents() *SourceSystemUpdateOne {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SyncEvent entities by IDs.
func (_u *SourceSystemUpdateOne) RemoveSyncEventIDs(ids ...uuid.UUID) *SourceSystemUpdateOne {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SyncEvent entities.
func (_u *SourceSystemUpdateOne) RemoveSyncEvents(v ...*SyncEvent) *SourceSystemUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// Where appends a list predicates to the SourceSystemUpdate builder.
func (_u *SourceSystemUpdateOne) Where(ps ...predicate.SourceSystem) *SourceSystemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceSystemUpdateOne) Select(field string, fields ...string) *SourceSystemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SourceSystem entity.
func (_u *SourceSystemUpdateOne) Save(ctx context.Context) (*SourceSystem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceSystemUpdateOne) SaveX(ctx context.Context) *SourceSystem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceSystemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceSystemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceSystemUpdateOne) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := sourcesystem.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

func (_u *SourceSystemUpdateOne) sqlSave(ctx context.Context) (_node *SourceSystem, err error) {
	_spec := sqlgraph.NewUpdateSpec(sourcesystem.Table, sourcesystem.Columns, sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SourceSystem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sourcesystem.FieldID)
		for _, f := range fields {
			if !sourcesystem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sourcesystem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(sourcesystem.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceSystemName(); ok {
		_spec.SetField(sourcesystem.FieldSourceSystemName, field.TypeString, value)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SourceSystem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sourcesystem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
