// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/sourcesystem"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/syncevent"
	"github.com/google/uuid"
)

// SourceSystemCreate is the builder for creating a SourceSystem entity.
type SourceSystemCreate struct {
	config
	mutation *SourceSystemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SourceSystemCreate) SetCreatedAt(v time.Time) *SourceSystemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SourceSystemCreate) SetNillableCreatedAt(v *time.Time) *SourceSystemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *SourceSystemCreate) SetModifiedAt(v time.Time) *SourceSystemCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *SourceSystemCreate) SetNillableModifiedAt(v *time.Time) *SourceSystemCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetSourceSystemName sets the "source_system_name" field.
func (_c *SourceSystemCreate) SetSourceSystemName(v string) *SourceSystemCreate {
	_c.mutation.SetSourceSystemName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SourceSystemCreate) SetID(v string) *SourceSystemCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSyncEventIDs adds the "sync_events" edge to the SyncEvent entity by IDs.
func (_c *SourceSystemCreate) AddSyncEventIDs(ids ...uuid.UUID) *SourceSystemCreate {
	_c.mutation.AddSyncEventIDs(ids...)
	return _c
}

// AddSyncEvents adds the "sync_events" edges to the SyncEvent entity.
func (_c *SourceSystemCreate) AddSyncEvents(v ...*SyncEvent) *SourceSystemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyncEventIDs(ids...)
}

// Mutation returns the SourceSystemMutation object of the builder.
func (_c *SourceSystemCreate) Mutation() *SourceSystemMutation {
	return _c.mutation
}

// Save creates the SourceSystem in the database.
func (_c *SourceSystemCreate) Save(ctx context.Context) (*SourceSystem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceSystemCreate) SaveX(ctx context.Context) *SourceSystem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceSystemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceSystemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceSystemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sourcesystem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		v := sourcesystem.DefaultModifiedAt()
		_c.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceSystemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SourceSystem.created_at"`)}
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New(`ent: missing required field "SourceSystem.modified_at"`)}
	}
	if _, ok := _c.mutation.SourceSystemName(); !ok {
		return &ValidationError{Name: "source_system_name", err: errors.New(`ent: missing required field "SourceSystem.source_system_name"`)}
	}
	return nil
}

func (_c *SourceSystemCreate) sqlSave(ctx context.Context) (*SourceSystem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SourceSystem.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceSystemCreate) createSpec() (*SourceSystem, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceSystem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sourcesystem.Table, sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sourcesystem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(sourcesystem.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := _c.mutation.SourceSystemName(); ok {
		_spec.SetField(sourcesystem.FieldSourceSystemName, field.TypeString, value)
		_node.SourceSystemName = value
	}
	if nodes := _c.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sourcesystem.SyncEventsTable,
			Columns: []string{sourcesystem.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceSystem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceSystemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceSystemCreate) OnConflict(opts ...sql.ConflictOption) *SourceSystemUpsertOne {
	_c.conflict = opts
	return &SourceSystemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceSystemCreate) OnConflictColumns(columns ...string) *SourceSystemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceSystemUpsertOne{
		create: _c,
	}
}

type (
	// SourceSystemUpsertOne is the builder for "upsert"-ing
	//  one SourceSystem node.
	SourceSystemUpsertOne struct {
		create *SourceSystemCreate
	}

	// SourceSystemUpsert is the "OnConflict" setter.
	SourceSystemUpsert struct {
		*sql.UpdateSet
	}
)

// SetModifiedAt sets the "modified_at" field.
func (u *SourceSystemUpsert) SetModifiedAt(v time.Time) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateModifiedAt() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldModifiedAt)
	return u
}

// SetSourceSystemName sets the "source_system_name" field.
func (u *SourceSystemUpsert) SetSourceSystemName(v string) *SourceSystemUpsert {
	u.Set(sourcesystem.FieldSourceSystemName, v)
	return u
}

// UpdateSourceSystemName sets the "source_system_name" field to the value that was provided on create.
func (u *SourceSystemUpsert) UpdateSourceSystemName() *SourceSystemUpsert {
	u.SetExcluded(sourcesystem.FieldSourceSystemName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sourcesystem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceSystemUpsertOne) UpdateNewValues() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sourcesystem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sourcesystem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SourceSystemUpsertOne) Ignore() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceSystemUpsertOne) DoNothing() *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceSystemCreate.OnConflict
// documentation for more info.
func (u *SourceSystemUpsertOne) Update(set func(*SourceSystemUpsert)) *SourceSystemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceSystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *SourceSystemUpsertOne) SetModifiedAt(v time.Time) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateModifiedAt() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetSourceSystemName sets the "source_system_name" field.
func (u *SourceSystemUpsertOne) SetSourceSystemName(v string) *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetSourceSystemName(v)
	})
}

// UpdateSourceSystemName sets the "source_system_name" field to the value that was provided on create.
func (u *SourceSystemUpsertOne) UpdateSourceSystemName() *SourceSystemUpsertOne {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateSourceSystemName()
	})
}

// Exec executes the query.
func (u *SourceSystemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceSystemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceSystemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SourceSystemUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SourceSystemUpsertOne.ID is not supported by MySQL driver. Use SourceSystemUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SourceSystemUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SourceSystemCreateBulk is the builder for creating many SourceSystem entities in bulk.
type SourceSystemCreateBulk struct {
	config
	err      error
	builders []*SourceSystemCreate
	conflict []sql.ConflictOption
}

// Save creates the SourceSystem entities in the database.
func (_c *SourceSystemCreateBulk) Save(ctx context.Context) ([]*SourceSystem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SourceSystem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceSystemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceSystemCreateBulk) SaveX(ctx context.Context) []*SourceSystem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceSystemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceSystemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SourceSystem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SourceSystemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SourceSystemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SourceSystemUpsertBulk {
	_c.conflict = opts
	return &SourceSystemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SourceSystemCreateBulk) OnConflictColumns(columns ...string) *SourceSystemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SourceSystemUpsertBulk{
		create: _c,
	}
}

// SourceSystemUpsertBulk is the builder for "upsert"-ing
// a bulk of SourceSystem nodes.
type SourceSystemUpsertBulk struct {
	create *SourceSystemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sourcesystem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SourceSystemUpsertBulk) UpdateNewValues() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sourcesystem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sourcesystem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SourceSystem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SourceSystemUpsertBulk) Ignore() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SourceSystemUpsertBulk) DoNothing() *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SourceSystemCreateBulk.OnConflict
// documentation for more info.
func (u *SourceSystemUpsertBulk) Update(set func(*SourceSystemUpsert)) *SourceSystemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SourceSystemUpsert{UpdateSet: update})
	}))
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *SourceSystemUpsertBulk) SetModifiedAt(v time.Time) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateModifiedAt() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetSourceSystemName sets the "source_system_name" field.
func (u *SourceSystemUpsertBulk) SetSourceSystemName(v string) *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.SetSourceSystemName(v)
	})
}

// UpdateSourceSystemName sets the "source_system_name" field to the value that was provided on create.
func (u *SourceSystemUpsertBulk) UpdateSourceSystemName() *SourceSystemUpsertBulk {
	return u.Update(func(s *SourceSystemUpsert) {
		s.UpdateSourceSystemName()
	})
}

// Exec executes the query.
func (u *SourceSystemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SourceSystemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SourceSystemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SourceSystemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
