// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/attachmentjob"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/predicate"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/rawoutput"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/sourcesystem"
	"github.com/LunarHUE/MLS-Grid-Sync/ent/syncevent"
	"github.com/google/uuid"
)

// SyncEventUpdate is the builder for updating SyncEvent entities.
type SyncEventUpdate struct {
	config
	hooks    []Hook
	mutation *SyncEventMutation
}

// Where appends a list predicates to the SyncEventUpdate builder.
func (_u *SyncEventUpdate) Where(ps ...predicate.SyncEvent) *SyncEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *SyncEventUpdate) SetModifiedAt(v time.Time) *SyncEventUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetSourceSystemID sets the "source_system_id" field.
func (_u *SyncEventUpdate) SetSourceSystemID(v string) *SyncEventUpdate {
	_u.mutation.SetSourceSystemID(v)
	return _u
}

// SetNillableSourceSystemID sets the "source_system_id" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableSourceSystemID(v *string) *SyncEventUpdate {
	if v != nil {
		_u.SetSourceSystemID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *SyncEventUpdate) SetResource(v syncevent.Resource) *SyncEventUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableResource(v *syncevent.Resource) *SyncEventUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetRunType sets the "run_type" field.
func (_u *SyncEventUpdate) SetRunType(v syncevent.RunType) *SyncEventUpdate {
	_u.mutation.SetRunType(v)
	return _u
}

// SetNillableRunType sets the "run_type" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableRunType(v *syncevent.RunType) *SyncEventUpdate {
	if v != nil {
		_u.SetRunType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncEventUpdate) SetStatus(v syncevent.Status) *SyncEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableStatus(v *syncevent.Status) *SyncEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *SyncEventUpdate) SetProcessorVersion(v string) *SyncEventUpdate {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableProcessorVersion(v *string) *SyncEventUpdate {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// SetReprocessOf sets the "reprocess_of" field.
func (_u *SyncEventUpdate) SetReprocessOf(v uuid.UUID) *SyncEventUpdate {
	_u.mutation.SetReprocessOf(v)
	return _u
}

// SetNillableReprocessOf sets the "reprocess_of" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableReprocessOf(v *uuid.UUID) *SyncEventUpdate {
	if v != nil {
		_u.SetReprocessOf(*v)
	}
	return _u
}

// ClearReprocessOf clears the value of the "reprocess_of" field.
func (_u *SyncEventUpdate) ClearReprocessOf() *SyncEventUpdate {
	_u.mutation.ClearReprocessOf()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncEventUpdate) SetStartedAt(v time.Time) *SyncEventUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableStartedAt(v *time.Time) *SyncEventUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SyncEventUpdate) SetEndedAt(v time.Time) *SyncEventUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableEndedAt(v *time.Time) *SyncEventUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SyncEventUpdate) ClearEndedAt() *SyncEventUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *SyncEventUpdate) SetRecordCount(v int) *SyncEventUpdate {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableRecordCount(v *int) *SyncEventUpdate {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *SyncEventUpdate) AddRecordCount(v int) *SyncEventUpdate {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetHighWaterMark sets the "high_water_mark" field.
func (_u *SyncEventUpdate) SetHighWaterMark(v time.Time) *SyncEventUpdate {
	_u.mutation.SetHighWaterMark(v)
	return _u
}

// SetNillableHighWaterMark sets the "high_water_mark" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableHighWaterMark(v *time.Time) *SyncEventUpdate {
	if v != nil {
		_u.SetHighWaterMark(*v)
	}
	return _u
}

// ClearHighWaterMark clears the value of the "high_water_mark" field.
func (_u *SyncEventUpdate) ClearHighWaterMark() *SyncEventUpdate {
	_u.mutation.ClearHighWaterMark()
	return _u
}

// SetErrorSummary sets the "error_summary" field.
func (_u *SyncEventUpdate) SetErrorSummary(v string) *SyncEventUpdate {
	_u.mutation.SetErrorSummary(v)
	return _u
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableErrorSummary(v *string) *SyncEventUpdate {
	if v != nil {
		_u.SetErrorSummary(*v)
	}
	return _u
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (_u *SyncEventUpdate) ClearErrorSummary() *SyncEventUpdate {
	_u.mutation.ClearErrorSummary()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *SyncEventUpdate) SetLogs(v []string) *SyncEventUpdate {
	_u.mutation.SetLogs(v)
	return _u
}

// AppendLogs appends value to the "logs" field.
func (_u *SyncEventUpdate) AppendLogs(v []string) *SyncEventUpdate {
	_u.mutation.AppendLogs(v)
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *SyncEventUpdate) ClearLogs() *SyncEventUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// SetSourceSystem sets the "source_system" edge to the SourceSystem entity.
func (_u *SyncEventUpdate) SetSourceSystem(v *SourceSystem) *SyncEventUpdate {
	return _u.SetSourceSystemID(v.ID)
}

// AddRawOutputIDs adds the "raw_outputs" edge to the RawOutput entity by IDs.
func (_u *SyncEventUpdate) AddRawOutputIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.AddRawOutputIDs(ids...)
	return _u
}

// AddRawOutputs adds the "raw_outputs" edges to the RawOutput entity.
func (_u *SyncEventUpdate) AddRawOutputs(v ...*RawOutput) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawOutputIDs(ids...)
}

// AddAttachmentJobIDs adds the "attachment_jobs" edge to the AttachmentJob entity by IDs.
func (_u *SyncEventUpdate) AddAttachmentJobIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.AddAttachmentJobIDs(ids...)
	return _u
}

// AddAttachmentJobs adds the "attachment_jobs" edges to the AttachmentJob entity.
func (_u *SyncEventUpdate) AddAttachmentJobs(v ...*AttachmentJob) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentJobIDs(ids...)
}

// SetOriginalSyncID sets the "original_sync" edge to the SyncEvent entity by ID.
func (_u *SyncEventUpdate) SetOriginalSyncID(id uuid.UUID) *SyncEventUpdate {
	_u.mutation.SetOriginalSyncID(id)
	return _u
}

// SetNillableOriginalSyncID sets the "original_sync" edge to the SyncEvent entity by ID if the given value is not nil.
func (_u *SyncEventUpdate) SetNillableOriginalSyncID(id *uuid.UUID) *SyncEventUpdate {
	if id != nil {
		_u = _u.SetOriginalSyncID(*id)
	}
	return _u
}

// SetOriginalSync sets the "original_sync" edge to the SyncEvent entity.
func (_u *SyncEventUpdate) SetOriginalSync(v *SyncEvent) *SyncEventUpdate {
	return _u.SetOriginalSyncID(v.ID)
}

// AddReprocessIDs adds the "reprocesses" edge to the SyncEvent entity by IDs.
func (_u *SyncEventUpdate) AddReprocessIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.AddReprocessIDs(ids...)
	return _u
}

// AddReprocesses adds the "reprocesses" edges to the SyncEvent entity.
func (_u *SyncEventUpdate) AddReprocesses(v ...*SyncEvent) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReprocessIDs(ids...)
}

// Mutation returns the SyncEventMutation object of the builder.
func (_u *SyncEventUpdate) Mutation() *SyncEventMutation {
	return _u.mutation
}

// ClearSourceSystem clears the "source_system" edge to the SourceSystem entity.
func (_u *SyncEventUpdate) ClearSourceSystem() *SyncEventUpdate {
	_u.mutation.ClearSourceSystem()
	return _u
}

// ClearRawOutputs clears all "raw_outputs" edges to the RawOutput entity.
func (_u *SyncEventUpdate) ClearRawOutputs() *SyncEventUpdate {
	_u.mutation.ClearRawOutputs()
	return _u
}

// RemoveRawOutputIDs removes the "raw_outputs" edge to RawOutput entities by IDs.
func (_u *SyncEventUpdate) RemoveRawOutputIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.RemoveRawOutputIDs(ids...)
	return _u
}

// RemoveRawOutputs removes "raw_outputs" edges to RawOutput entities.
func (_u *SyncEventUpdate) RemoveRawOutputs(v ...*RawOutput) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawOutputIDs(ids...)
}

// ClearAttachmentJobs clears all "attachment_jobs" edges to the AttachmentJob entity.
func (_u *SyncEventUpdate) ClearAttachmentJobs() *SyncEventUpdate {
	_u.mutation.ClearAttachmentJobs()
	return _u
}

// RemoveAttachmentJobIDs removes the "attachment_jobs" edge to AttachmentJob entities by IDs.
func (_u *SyncEventUpdate) RemoveAttachmentJobIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.RemoveAttachmentJobIDs(ids...)
	return _u
}

// RemoveAttachmentJobs removes "attachment_jobs" edges to AttachmentJob entities.
func (_u *SyncEventUpdate) RemoveAttachmentJobs(v ...*AttachmentJob) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentJobIDs(ids...)
}

// ClearOriginalSync clears the "original_sync" edge to the SyncEvent entity.
func (_u *SyncEventUpdate) ClearOriginalSync() *SyncEventUpdate {
	_u.mutation.ClearOriginalSync()
	return _u
}

// ClearReprocesses clears all "reprocesses" edges to the SyncEvent entity.
func (_u *SyncEventUpdate) ClearReprocesses() *SyncEventUpdate {
	_u.mutation.ClearReprocesses()
	return _u
}

// RemoveReprocessIDs removes the "reprocesses" edge to SyncEvent entities by IDs.
func (_u *SyncEventUpdate) RemoveReprocessIDs(ids ...uuid.UUID) *SyncEventUpdate {
	_u.mutation.RemoveReprocessIDs(ids...)
	return _u
}

// RemoveReprocesses removes "reprocesses" edges to SyncEvent entities.
func (_u *SyncEventUpdate) RemoveReprocesses(v ...*SyncEvent) *SyncEventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReprocessIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncEventUpdate) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := syncevent.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncEventUpdate) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := syncevent.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunType(); ok {
		if err := syncevent.RunTypeValidator(v); err != nil {
			return &ValidationError{Name: "run_type", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.run_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.status": %w`, err)}
		}
	}
	if _u.mutation.SourceSystemCleared() && len(_u.mutation.SourceSystemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncEvent.source_system"`)
	}
	return nil
}

func (_u *SyncEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncevent.Table, syncevent.Columns, sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(syncevent.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(syncevent.FieldResource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RunType(); ok {
		_spec.SetField(syncevent.FieldRunType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(syncevent.FieldProcessorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncevent.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(syncevent.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(syncevent.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(syncevent.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(syncevent.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HighWaterMark(); ok {
		_spec.SetField(syncevent.FieldHighWaterMark, field.TypeTime, value)
	}
	if _u.mutation.HighWaterMarkCleared() {
		_spec.ClearField(syncevent.FieldHighWaterMark, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorSummary(); ok {
		_spec.SetField(syncevent.FieldErrorSummary, field.TypeString, value)
	}
	if _u.mutation.ErrorSummaryCleared() {
		_spec.ClearField(syncevent.FieldErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(syncevent.FieldLogs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLogs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, syncevent.FieldLogs, value)
		})
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(syncevent.FieldLogs, field.TypeJSON)
	}
	if _u.mutation.SourceSystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.SourceSystemTable,
			Columns: []string{syncevent.SourceSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceSystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.SourceSystemTable,
			Columns: []string{syncevent.SourceSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RawOutputsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawOutputsIDs(); len(nodes) > 0 && !_u.mutation.RawOutputsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawOutputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentJobsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OriginalSyncCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.OriginalSyncTable,
			Columns: []string{syncevent.OriginalSyncColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OriginalSyncIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.OriginalSyncTable,
			Columns: []string{syncevent.OriginalSyncColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReprocessesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReprocessesIDs(); len(nodes) > 0 && !_u.mutation.ReprocessesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReprocessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncEventUpdateOne is the builder for updating a single SyncEvent entity.
type SyncEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncEventMutation
}

// SetModifiedAt sets the "modified_at" field.
func (_u *SyncEventUpdateOne) SetModifiedAt(v time.Time) *SyncEventUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetSourceSystemID sets the "source_system_id" field.
func (_u *SyncEventUpdateOne) SetSourceSystemID(v string) *SyncEventUpdateOne {
	_u.mutation.SetSourceSystemID(v)
	return _u
}

// SetNillableSourceSystemID sets the "source_system_id" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableSourceSystemID(v *string) *SyncEventUpdateOne {
	if v != nil {
		_u.SetSourceSystemID(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *SyncEventUpdateOne) SetResource(v syncevent.Resource) *SyncEventUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableResource(v *syncevent.Resource) *SyncEventUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetRunType sets the "run_type" field.
func (_u *SyncEventUpdateOne) SetRunType(v syncevent.RunType) *SyncEventUpdateOne {
	_u.mutation.SetRunType(v)
	return _u
}

// SetNillableRunType sets the "run_type" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableRunType(v *syncevent.RunType) *SyncEventUpdateOne {
	if v != nil {
		_u.SetRunType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncEventUpdateOne) SetStatus(v syncevent.Status) *SyncEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableStatus(v *syncevent.Status) *SyncEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProcessorVersion sets the "processor_version" field.
func (_u *SyncEventUpdateOne) SetProcessorVersion(v string) *SyncEventUpdateOne {
	_u.mutation.SetProcessorVersion(v)
	return _u
}

// SetNillableProcessorVersion sets the "processor_version" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableProcessorVersion(v *string) *SyncEventUpdateOne {
	if v != nil {
		_u.SetProcessorVersion(*v)
	}
	return _u
}

// SetReprocessOf sets the "reprocess_of" field.
func (_u *SyncEventUpdateOne) SetReprocessOf(v uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.SetReprocessOf(v)
	return _u
}

// SetNillableReprocessOf sets the "reprocess_of" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableReprocessOf(v *uuid.UUID) *SyncEventUpdateOne {
	if v != nil {
		_u.SetReprocessOf(*v)
	}
	return _u
}

// ClearReprocessOf clears the value of the "reprocess_of" field.
func (_u *SyncEventUpdateOne) ClearReprocessOf() *SyncEventUpdateOne {
	_u.mutation.ClearReprocessOf()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncEventUpdateOne) SetStartedAt(v time.Time) *SyncEventUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableStartedAt(v *time.Time) *SyncEventUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SyncEventUpdateOne) SetEndedAt(v time.Time) *SyncEventUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableEndedAt(v *time.Time) *SyncEventUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SyncEventUpdateOne) ClearEndedAt() *SyncEventUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *SyncEventUpdateOne) SetRecordCount(v int) *SyncEventUpdateOne {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableRecordCount(v *int) *SyncEventUpdateOne {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *SyncEventUpdateOne) AddRecordCount(v int) *SyncEventUpdateOne {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetHighWaterMark sets the "high_water_mark" field.
func (_u *SyncEventUpdateOne) SetHighWaterMark(v time.Time) *SyncEventUpdateOne {
	_u.mutation.SetHighWaterMark(v)
	return _u
}

// SetNillableHighWaterMark sets the "high_water_mark" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableHighWaterMark(v *time.Time) *SyncEventUpdateOne {
	if v != nil {
		_u.SetHighWaterMark(*v)
	}
	return _u
}

// ClearHighWaterMark clears the value of the "high_water_mark" field.
func (_u *SyncEventUpdateOne) ClearHighWaterMark() *SyncEventUpdateOne {
	_u.mutation.ClearHighWaterMark()
	return _u
}

// SetErrorSummary sets the "error_summary" field.
func (_u *SyncEventUpdateOne) SetErrorSummary(v string) *SyncEventUpdateOne {
	_u.mutation.SetErrorSummary(v)
	return _u
}

// SetNillableErrorSummary sets the "error_summary" field if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableErrorSummary(v *string) *SyncEventUpdateOne {
	if v != nil {
		_u.SetErrorSummary(*v)
	}
	return _u
}

// ClearErrorSummary clears the value of the "error_summary" field.
func (_u *SyncEventUpdateOne) ClearErrorSummary() *SyncEventUpdateOne {
	_u.mutation.ClearErrorSummary()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *SyncEventUpdateOne) SetLogs(v []string) *SyncEventUpdateOne {
	_u.mutation.SetLogs(v)
	return _u
}

// AppendLogs appends value to the "logs" field.
func (_u *SyncEventUpdateOne) AppendLogs(v []string) *SyncEventUpdateOne {
	_u.mutation.AppendLogs(v)
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *SyncEventUpdateOne) ClearLogs() *SyncEventUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// SetSourceSystem sets the "source_system" edge to the SourceSystem entity.
func (_u *SyncEventUpdateOne) SetSourceSystem(v *SourceSystem) *SyncEventUpdateOne {
	return _u.SetSourceSystemID(v.ID)
}

// AddRawOutputIDs adds the "raw_outputs" edge to the RawOutput entity by IDs.
func (_u *SyncEventUpdateOne) AddRawOutputIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.AddRawOutputIDs(ids...)
	return _u
}

// AddRawOutputs adds the "raw_outputs" edges to the RawOutput entity.
func (_u *SyncEventUpdateOne) AddRawOutputs(v ...*RawOutput) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawOutputIDs(ids...)
}

// AddAttachmentJobIDs adds the "attachment_jobs" edge to the AttachmentJob entity by IDs.
func (_u *SyncEventUpdateOne) AddAttachmentJobIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.AddAttachmentJobIDs(ids...)
	return _u
}

// AddAttachmentJobs adds the "attachment_jobs" edges to the AttachmentJob entity.
func (_u *SyncEventUpdateOne) AddAttachmentJobs(v ...*AttachmentJob) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentJobIDs(ids...)
}

// SetOriginalSyncID sets the "original_sync" edge to the SyncEvent entity by ID.
func (_u *SyncEventUpdateOne) SetOriginalSyncID(id uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.SetOriginalSyncID(id)
	return _u
}

// SetNillableOriginalSyncID sets the "original_sync" edge to the SyncEvent entity by ID if the given value is not nil.
func (_u *SyncEventUpdateOne) SetNillableOriginalSyncID(id *uuid.UUID) *SyncEventUpdateOne {
	if id != nil {
		_u = _u.SetOriginalSyncID(*id)
	}
	return _u
}

// SetOriginalSync sets the "original_sync" edge to the SyncEvent entity.
func (_u *SyncEventUpdateOne) SetOriginalSync(v *SyncEvent) *SyncEventUpdateOne {
	return _u.SetOriginalSyncID(v.ID)
}

// AddReprocessIDs adds the "reprocesses" edge to the SyncEvent entity by IDs.
func (_u *SyncEventUpdateOne) AddReprocessIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.AddReprocessIDs(ids...)
	return _u
}

// AddReprocesses adds the "reprocesses" edges to the SyncEvent entity.
func (_u *SyncEventUpdateOne) AddReprocesses(v ...*SyncEvent) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReprocessIDs(ids...)
}

// Mutation returns the SyncEventMutation object of the builder.
func (_u *SyncEventUpdateOne) Mutation() *SyncEventMutation {
	return _u.mutation
}

// ClearSourceSystem clears the "source_system" edge to the SourceSystem entity.
func (_u *SyncEventUpdateOne) ClearSourceSystem() *SyncEventUpdateOne {
	_u.mutation.ClearSourceSystem()
	return _u
}

// ClearRawOutputs clears all "raw_outputs" edges to the RawOutput entity.
func (_u *SyncEventUpdateOne) ClearRawOutputs() *SyncEventUpdateOne {
	_u.mutation.ClearRawOutputs()
	return _u
}

// RemoveRawOutputIDs removes the "raw_outputs" edge to RawOutput entities by IDs.
func (_u *SyncEventUpdateOne) RemoveRawOutputIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.RemoveRawOutputIDs(ids...)
	return _u
}

// RemoveRawOutputs removes "raw_outputs" edges to RawOutput entities.
func (_u *SyncEventUpdateOne) RemoveRawOutputs(v ...*RawOutput) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawOutputIDs(ids...)
}

// ClearAttachmentJobs clears all "attachment_jobs" edges to the AttachmentJob entity.
func (_u *SyncEventUpdateOne) ClearAttachmentJobs() *SyncEventUpdateOne {
	_u.mutation.ClearAttachmentJobs()
	return _u
}

// RemoveAttachmentJobIDs removes the "attachment_jobs" edge to AttachmentJob entities by IDs.
func (_u *SyncEventUpdateOne) RemoveAttachmentJobIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.RemoveAttachmentJobIDs(ids...)
	return _u
}

// RemoveAttachmentJobs removes "attachment_jobs" edges to AttachmentJob entities.
func (_u *SyncEventUpdateOne) RemoveAttachmentJobs(v ...*AttachmentJob) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentJobIDs(ids...)
}

// ClearOriginalSync clears the "original_sync" edge to the SyncEvent entity.
func (_u *SyncEventUpdateOne) ClearOriginalSync() *SyncEventUpdateOne {
	_u.mutation.ClearOriginalSync()
	return _u
}

// ClearReprocesses clears all "reprocesses" edges to the SyncEvent entity.
func (_u *SyncEventUpdateOne) ClearReprocesses() *SyncEventUpdateOne {
	_u.mutation.ClearReprocesses()
	return _u
}

// RemoveReprocessIDs removes the "reprocesses" edge to SyncEvent entities by IDs.
func (_u *SyncEventUpdateOne) RemoveReprocessIDs(ids ...uuid.UUID) *SyncEventUpdateOne {
	_u.mutation.RemoveReprocessIDs(ids...)
	return _u
}

// RemoveReprocesses removes "reprocesses" edges to SyncEvent entities.
func (_u *SyncEventUpdateOne) RemoveReprocesses(v ...*SyncEvent) *SyncEventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReprocessIDs(ids...)
}

// Where appends a list predicates to the SyncEventUpdate builder.
func (_u *SyncEventUpdateOne) Where(ps ...predicate.SyncEvent) *SyncEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncEventUpdateOne) Select(field string, fields ...string) *SyncEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncEvent entity.
func (_u *SyncEventUpdateOne) Save(ctx context.Context) (*SyncEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncEventUpdateOne) SaveX(ctx context.Context) *SyncEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncEventUpdateOne) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := syncevent.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncEventUpdateOne) check() error {
	if v, ok := _u.mutation.Resource(); ok {
		if err := syncevent.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RunType(); ok {
		if err := syncevent.RunTypeValidator(v); err != nil {
			return &ValidationError{Name: "run_type", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.run_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := syncevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.status": %w`, err)}
		}
	}
	if _u.mutation.SourceSystemCleared() && len(_u.mutation.SourceSystemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SyncEvent.source_system"`)
	}
	return nil
}

func (_u *SyncEventUpdateOne) sqlSave(ctx context.Context) (_node *SyncEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncevent.Table, syncevent.Columns, sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncevent.FieldID)
		for _, f := range fields {
			if !syncevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(syncevent.FieldModifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(syncevent.FieldResource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RunType(); ok {
		_spec.SetField(syncevent.FieldRunType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProcessorVersion(); ok {
		_spec.SetField(syncevent.FieldProcessorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncevent.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(syncevent.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(syncevent.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(syncevent.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(syncevent.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HighWaterMark(); ok {
		_spec.SetField(syncevent.FieldHighWaterMark, field.TypeTime, value)
	}
	if _u.mutation.HighWaterMarkCleared() {
		_spec.ClearField(syncevent.FieldHighWaterMark, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorSummary(); ok {
		_spec.SetField(syncevent.FieldErrorSummary, field.TypeString, value)
	}
	if _u.mutation.ErrorSummaryCleared() {
		_spec.ClearField(syncevent.FieldErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(syncevent.FieldLogs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLogs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, syncevent.FieldLogs, value)
		})
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(syncevent.FieldLogs, field.TypeJSON)
	}
	if _u.mutation.SourceSystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.SourceSystemTable,
			Columns: []string{syncevent.SourceSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceSystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.SourceSystemTable,
			Columns: []string{syncevent.SourceSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sourcesystem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RawOutputsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawOutputsIDs(); len(nodes) > 0 && !_u.mutation.RawOutputsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawOutputsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.RawOutputsTable,
			Columns: []string{syncevent.RawOutputsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rawoutput.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentJobsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.AttachmentJobsTable,
			Columns: []string{syncevent.AttachmentJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachmentjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OriginalSyncCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.OriginalSyncTable,
			Columns: []string{syncevent.OriginalSyncColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OriginalSyncIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.OriginalSyncTable,
			Columns: []string{syncevent.OriginalSyncColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReprocessesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReprocessesIDs(); len(nodes) > 0 && !_u.mutation.ReprocessesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReprocessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   syncevent.ReprocessesTable,
			Columns: []string{syncevent.ReprocessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SyncEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
