// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// AttachmentJob is the predicate function for attachmentjob builders.
type AttachmentJob func(*sql.Selector)

// Lookup is the predicate function for lookup builders.
type Lookup func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// MediaVersion is the predicate function for mediaversion builders.
type MediaVersion func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// MemberVersion is the predicate function for memberversion builders.
type MemberVersion func(*sql.Selector)

// Office is the predicate function for office builders.
type Office func(*sql.Selector)

// OfficeVersion is the predicate function for officeversion builders.
type OfficeVersion func(*sql.Selector)

// OpenHouse is the predicate function for openhouse builders.
type OpenHouse func(*sql.Selector)

// OpenHouseVersion is the predicate function for openhouseversion builders.
type OpenHouseVersion func(*sql.Selector)

// ProcessorCursor is the predicate function for processorcursor builders.
type ProcessorCursor func(*sql.Selector)

// Property is the predicate function for property builders.
type Property func(*sql.Selector)

// PropertyRoom is the predicate function for propertyroom builders.
type PropertyRoom func(*sql.Selector)

// PropertyRoomVersion is the predicate function for propertyroomversion builders.
type PropertyRoomVersion func(*sql.Selector)

// PropertyUnitType is the predicate function for propertyunittype builders.
type PropertyUnitType func(*sql.Selector)

// PropertyUnitTypeVersion is the predicate function for propertyunittypeversion builders.
type PropertyUnitTypeVersion func(*sql.Selector)

// PropertyVersion is the predicate function for propertyversion builders.
type PropertyVersion func(*sql.Selector)

// RawOutput is the predicate function for rawoutput builders.
type RawOutput func(*sql.Selector)

// SourceSystem is the predicate function for sourcesystem builders.
type SourceSystem func(*sql.Selector)

// SyncEvent is the predicate function for syncevent builders.
type SyncEvent func(*sql.Selector)
